/* Тексты панели оператора. Панель только на русском: ею пользуется команда, не клиенты.
   Узбекские здесь — только подписи полей, куда вписывают текст для клиентов на узбекском. */
export const t = {
  area: "панель оператора",
  skip: "К содержимому",
  sections: "Разделы панели",
  vendors: "Вендоры",
  vendorsLead: "Карточки вендоров: создание, правка, отметка о проверке.",
  moderation: "Модерация",
  moderationLead:
    "Карточки на проверке, правки опубликованных карточек, услуги и новые фото — всё, что ждёт решения.",
  requests: "Заявки",
  requestsLead: "Заявки клиентов и ответы вендоров. Без ответа дольше 12 часов — вверху.",
  clients: "Клиенты",
  clientsLead:
    "Клиенты — под псевдонимом: поиск по номеру заявки или коду клиента. Выгрузки базы клиентов нет.",
  notifications: "Уведомления",
  notificationsLead: "Очередь сообщений бота: сколько ждёт отправки и что не доставлено.",
  audit: "Журнал",
  auditLead: "Кто, что и когда сделал в панели, и кто смотрел телефоны. Только чтение.",
  team: "Команда",
  teamLead: "Сотрудники панели: приглашение по имени в Telegram или по номеру телефона, роли, отключение.",
  settings: "Настройки",
  settingsLead: "Срок ответа, напоминания, фото, лимиты и сроки хранения. Каждое изменение — в журнале.",
  metrics: "Метрики",
  metricsLead:
    "Главное на запуске: клиент отправил заявку — площадка ответила в срок. Только числа: по неделям и по вендорам.",
  noAccess: "У вашей роли нет доступа к этому разделу.",
  soon: "Раздел в разработке",
  notFound: "Страница не найдена",
  notFoundLead: "Проверьте адрес или откройте список вендоров.",
  toHome: "К вендорам",
  toSection: (section: string) => `Открыть «${section}»`,

  // несохранённые правки: уход со страницы
  unsavedTitle: "Уйти без сохранения?",
  unsavedText: "Изменения на этой странице не сохранены. Если уйти, они пропадут.",
  unsavedLeave: "Уйти",
  unsavedStay: "Остаться",

  // вход
  login: "Вход для сотрудников",
  loginLead:
    "Вход — аккаунтом Bayramm на сайте: через Telegram или по телефону. Доступ открывает администратор — по приглашению на ваше имя пользователя в Telegram или номер телефона.",
  // то же, когда входа по телефону в этом окружении нет (GET /auth/methods → phone: false)
  loginLeadTelegram:
    "Вход — аккаунтом Bayramm на сайте через Telegram. Доступ открывает администратор — по приглашению на ваше имя пользователя в Telegram.",
  loginChecking: "Проверяем вход…",
  loginHub: "Войти через Bayramm",
  loginStarting: "Переходим ко входу…",
  loginMiniApp: "В Telegram панель открывается кнопкой «Панель оператора» в боте.",
  loginOpenBot: "Открыть бота",
  toClientApp: "Приложение Bayramm",
  toCabinet: "Кабинет партнёра",
  retry: "Повторить",
  signOut: "Выйти",
  signedInAs: "Вы вошли как",
  errors: {
    invalid: "Вход не завершился или ссылка входа устарела. Войдите ещё раз.",
    denied:
      "Нет доступа к панели. Если вас пригласили, проверьте имя пользователя в Telegram или обратитесь к администратору.",
    reauth: "Вход был больше 12 часов назад. Войдите ещё раз — панель открывается только по свежему входу.",
    unavailable: "Сервер не отвечает. Попробуйте ещё раз через минуту.",
    expired:
      "Сессия закончилась: вход в панель действует 12 часов. Войдите ещё раз — откроется тот же экран.",
  },
  roles: {
    admin: "Администратор",
    manager: "Менеджер",
    moderator: "Модератор",
  },

  // заголовки экранов внутри разделов
  views: {
    vendorNew: "Новый вендор",
    vendor: "Вендор",
    listingNew: "Новая витрина",
    listing: "Карточка",
    request: "Заявка",
    client: "Клиент",
    revision: "Правка карточки",
  },

  // общее
  loading: "Загружаем…",
  save: "Сохранить",
  saving: "Сохраняем…",
  saved: "Сохранено",
  cancel: "Отмена",
  back: "Назад",
  search: "Поиск",
  // кнопки своих контролов (@bayramm/ui/react): крестик шторки и очистка поля поиска
  close: "Закрыть",
  clear: "Очистить",
  // связь
  offline: "Нет подключения к интернету. Когда связь вернётся, данные загрузятся сами.",
  backOnline: "Связь вернулась.",
  all: "Все",
  none: "—",
  show: "Показать",
  hidden: "скрыт",
  notSet: "не указан",
  more: "Ещё",
  optional: "по желанию",

  // телефон и планшет: шапка, нижняя панель, шторки
  account: "Аккаунт",
  accountOf: (name: string, role: string) => `Аккаунт: ${name}, ${role}`,
  moreSections: "Ещё разделы",
  moreCurrent: (section: string) => `Ещё, открыт раздел «${section}»`,
  // Счётчики у разделов (из очередей метрик): что ждёт команду
  badges: {
    requests: (n: number) => `просрочено: ${n}`,
    moderation: (n: number) => `ждут решения: ${n}`,
    notifications: (n: number) => `не доставлено: ${n}`,
  },
  filters: "Фильтры",
  sort: "Сортировка",
  done: "Готово",
  reset: "Сбросить",
  actionsTitle: "Действия",
  listingActionsContext: "действия с карточкой",
  shownOnly: (what: string) => `Показаны: ${what}`,
  scrollHint: "Таблица шире экрана — листайте вбок",
  total: (n: number) => `Всего: ${n}`,
  // Коды ошибок API → понятный текст. Неизвестный код — общий текст
  api: {
    network: "Нет связи с сервером. Проверьте соединение и попробуйте ещё раз.",
    unknown: "Что-то пошло не так. Попробуйте ещё раз.",
    internal_error: "Ошибка на сервере. Попробуйте ещё раз через минуту.",
    service_unavailable: "Сервер временно недоступен. Попробуйте через минуту.",
    forbidden: "Для этого действия у вашей роли нет прав.",
    not_found: "Не найдено: возможно, запись удалили или адрес неверный.",
    invalid_input: "Проверьте выделенные поля.",
    invalid_request: "Запрос не принят. Обновите страницу и попробуйте ещё раз.",
    payload_too_large: "Слишком большой файл или текст.",
    version_conflict: "Карточку только что изменили. Обновите страницу — ваши правки не сохранены.",
    illegal_transition: "Из текущего статуса так нельзя. Обновите страницу.",
    publish_blocked: "Не хватает данных для этого шага:",
    reason_required: "Нужна причина.",
    slug_taken: "Этот адрес карточки уже занят — выберите другой.",
    stir_taken: "Этот СТИР уже у другого вендора.",
    phone_taken: "Этот номер уже заведён для входа у этого вендора.",
    duplicate_package: "Два пакета одного вида. Оставьте один.",
    user_linked: "Пользователь уже привязал Telegram — номер не сменить. Отключите его и заведите нового.",
    stir_missing: "Сначала впишите СТИР в реквизиты.",
    consent_text_missing: "Нет действующего текста согласия на обработку ПДн. Обратитесь к администратору.",
    checklist_locked: "Отметку не снять, пока карточки вендора опубликованы — сначала приостановите их.",
    too_many_photos: "Больше фото не добавить — достигнут предел.",
    duplicate_photo: "Это фото уже загружено.",
    invalid_image: "Фото не принято.",
    no_faces_ack_required: "Подтвердите, что на фото нет лиц.",
    photo_consent_required: "Подтвердите, что люди на фото согласны на публикацию.",
    photo_ack_required: "Отметка на фото не подходит категории: для неё фото должны быть без лиц.",
    category_locked:
      "Категорию не сменить: у витрины уже есть заявки или услуги. Заведите вендору новую витрину в нужной категории.",
    service_not_allowed: "Эта услуга недоступна для витрины.",
    service_invalid: "Предложение не проходит проверку полей услуги — его можно только отклонить.",
    too_many_services: "У витрины уже предельное число услуг.",
    no_changes: "Изменений нет — сохранять нечего.",
    storage_unavailable: "Хранилище фото недоступно. Попробуйте позже.",
    forbidden_for_actor: "Это действие недоступно.",
    moderated_field_requires_revision: "Поле меняется только через модерацию.",
    reminder_too_soon:
      "Вендору недавно уже напоминали — пауза между напоминаниями ещё не прошла. Попробуйте позже или позвоните.",
    request_not_awaiting: "Заявка уже не ждёт ответа вендора.",
    vendor_unreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните вендору.",
    staff_self: "Себя нельзя отключить или сменить себе роль.",
    staff_last_admin: "Должен остаться хотя бы один действующий администратор.",
    username_taken: "Это имя в Telegram уже у действующего сотрудника.",
    staff_phone_taken:
      "Этот номер уже у сотрудника команды. Если сотрудник отключён — включите его в списке ниже.",
    revision_invalid: "Правка не проходит проверку полей — её можно только отклонить.",
    revision_pending:
      "У карточки уже есть правка, которая ждёт решения модератора. Пока по ней не решат, название и описания не изменить — ничего не сохранено.",
    calendar_conflict: "Календарь изменили — показали актуальный. Отметьте день ещё раз.",
    date_out_of_range: "Прошедший день не отметить и не снять. Если страница открыта давно — обновите её.",
    version_required: "Календарь устарел. Обновите страницу и отметьте день ещё раз.",
    client_blocked: "Клиент заблокирован.",
    // Общие ответы API, которые панель тоже может получить
    unauthorized: "Сессия закончилась. Войдите ещё раз.",
    reauth_required: "Вход был больше 12 часов назад. Войдите ещё раз.",
    account_disabled: "Аккаунт отключён. Обратитесь к администратору.",
    rate_limited: "Слишком много запросов подряд. Подождите минуту и попробуйте ещё раз.",
    conflict: "Такая запись уже есть. Обновите страницу и проверьте.",
    rule_violation: "Действие не прошло проверку правил. Обновите страницу и попробуйте ещё раз.",
    append_only: "Эту запись нельзя изменить или удалить — только добавить новую.",
    immutable_column: "Это поле после создания не меняется.",
    listing_not_active: "Карточка не опубликована — это действие недоступно.",
    consent_text_not_current: "Текст согласия обновился. Обновите страницу.",
  } as Record<string, string>,

  // статусы карточки
  status: {
    lead: "Лид",
    draft: "Черновик",
    review: "На проверке",
    active: "Опубликована",
    suspended: "Приостановлена",
    rejected: "Отклонена",
  },
  // Чего не хватает для проверки или публикации — коды app.listing_publish_blockers
  blockers: {
    price: "Услуга с ценой",
    capacity: "Вместимость (максимум гостей)",
    district: "Район",
    descriptions: "Описание на русском и узбекском",
    phone: "Телефон для заявок",
    packages: "Обязательные услуги категории",
    attributes: "Обязательные данные витрины",
    photos: "Фото: минимум 3 (для публикации — одобренные)",
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pd_consent: "Согласие на обработку ПДн подписано",
  } as Record<string, string>,
  blockersReview: "Не хватает для проверки",
  blockersActive: "Не хватает для публикации",
  readyToPublish: "Всё готово к публикации",
  legalForms: { ooo: "ООО", yatt: "ЯТТ (ИП)", self_employed: "Самозанятый" },
  priceUnits: {
    per_guest: "за гостя",
    per_event: "за мероприятие",
    per_hour: "за час",
    per_item: "за штуку",
    per_kg: "за кг",
    per_set: "за комплект",
    per_table: "за стол",
  },
  sum: "сум",

  // список вендоров
  newVendor: "Новый вендор",
  vendorsSearch: "Название, код, СТИР, телефон, контакт",
  vendorsEmpty: "Вендоров не нашлось.",
  vendorsEmptyAll: "Вендоров пока нет. Начните с «Новый вендор».",
  colVendor: "Вендор",
  colContact: "Контакт",
  colListings: "Витрины",
  colChecklist: "Проверка",
  colCabinet: "Кабинет",
  cabinetUsers: (users: number, linked: number) =>
    users === 0 ? "нет входа" : `${linked} из ${users} в Telegram`,
  noListings: "нет витрин",

  // вендор
  vendorCode: "Код",
  vendorSections: {
    business: "Бизнес",
    businessHint: "Название для панели и реквизиты. Скан документов не храним — только отметку о проверке.",
    contact: "Контакт",
    contactHint:
      "Контактное лицо вендора. Телефоны видны только по кнопке «Показать» — просмотр пишется в журнал.",
  },
  fields: {
    name: "Название",
    legalForm: "Форма",
    legalName: "Юрназвание",
    stir: "СТИР (9 цифр)",
    legalAddress: "Юрадрес",
    contractNo: "Номер договора",
    managerId: "Менеджер",
    contactPerson: "Контактное лицо",
    contactRole: "Должность",
    phone: "Телефон",
    phoneAlt: "Второй телефон",
    telegramUsername: "Telegram (@имя)",
  } as Record<string, string>,
  fieldErrors: {
    name: "От 2 до 120 символов",
    stir: "Ровно 9 цифр",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    phoneAlt: "Номер Узбекистана: +998 и 9 цифр",
    telegramUsername: "5–32 символа: латиница, цифры, _",
  } as Record<string, string>,
  phoneKeep: "Оставьте пустым, чтобы не менять",
  phoneNew: "Новый номер",
  createVendor: "Создать вендора",
  vendorReadOnly: "Только просмотр: данные вендора меняют менеджер и администратор.",
  noManager: "Не назначен",

  checklist: "Проверка вендора",
  checklistHint: "Все четыре отметки нужны для публикации. Каждая отметка — в журнале действий.",
  checklistItems: {
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pdConsent: "Согласие на обработку ПДн подписано",
  },
  checkedBy: (by: string | null, at: string) => (by ? `${by}, ${at}` : at),
  phones: "Телефоны контакта",
  phoneMain: "Основной",
  phoneAlternative: "Второй",

  users: "Вход в кабинет",
  usersHint:
    "Заведите пользователя по номеру телефона. Вендор привяжет Telegram сам: откроет бота и поделится контактом с этого номера.",
  usersEmpty: "Пока никого нет.",
  addUser: "Добавить",
  userPhone: "Телефон для входа",
  userName: "Имя",
  telegramLinked: "Telegram привязан",
  telegramNotLinked: "Ждём привязки Telegram",
  userDisabled: "Отключён",
  disable: "Отключить",
  unlinkTelegram: "Отвязать Telegram",
  unlinkHint: "Бот перестанет присылать этому человеку заявки, пока он снова не поделится номером.",
  disableUserHint: "Человек сразу потеряет вход в кабинет. Включить его можно в любой момент.",
  enable: "Включить",
  owner: "Владелец",
  member: "Сотрудник",

  listings: "Витрины",
  newListing: "Новая витрина",
  listingsEmpty: "У вендора пока нет витрин.",

  // карточка
  listingSections: {
    main: "Карточка",
    mainHint: "Название, адрес карточки и район. Адрес карточки (латиница) — в ссылке на неё.",
    texts: "Описание и адрес",
    textsHint: "На двух языках: клиент видит свой.",
    prices: "Цены и вместимость",
    pricesHint: "Цена обязательна: «по запросу» не бывает. Пакеты будней и выходных — обязательны для залов.",
    phone: "Телефон для заявок",
    phoneHint: "Клиент видит его сразу, до заявки.",
  },
  listingFields: {
    name: "Название",
    slug: "Адрес карточки",
    districtCode: "Район",
    addressRu: "Адрес (RU)",
    addressUz: "Manzil (UZ)",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    priceFromUzs: "Цена от, сум",
    priceUnit: "За что",
    capMin: "Гостей от",
    capMax: "Гостей до",
    phone: "Телефон",
    status: "Статус",
  } as Record<string, string>,
  listingFieldErrors: {
    name: "От 2 до 80 символов",
    slug: "Латиница, цифры и дефис, 3–40 символов",
    capMax: "Не меньше, чем «гостей от»",
    priceFromUzs: "Целое число больше нуля",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    packages: "Проверьте пакеты: у каждого названия на двух языках и цена",
  } as Record<string, string>,
  slugAuto: "Сформируется из названия",
  category: "Категория",
  packages: "Пакеты",
  packageKinds: { weekday: "Будни", weekend: "Выходные", custom: "Свой пакет" },
  packageDefaults: {
    weekday: { ru: "Будни", uz: "Ish kunlari" },
    weekend: { ru: "Выходные", uz: "Dam olish kunlari" },
  },
  packageNameRu: "Название (RU)",
  packageNameUz: "Nomi (UZ)",
  packagePrice: "Цена, сум",
  addPackage: "Добавить пакет",
  removePackage: "Убрать",
  createListing: "Создать карточку",
  listingReadOnly: "Только просмотр: поля карточки меняют менеджер и администратор.",
  startAs: "Создать как",
  phoneSet: "Телефон вписан",
  phoneMissing: "Телефона нет",
  phoneChange: "Сменить номер",
  history: "История статусов",
  historyEmpty: "Пока без изменений.",
  historyBy: {
    staff: "сотрудник",
    vendor_user: "вендор",
    system: "система",
    client: "клиент",
    account: "аккаунт",
  } as Record<string, string>,
  openVendor: "К вендору",
  statusReason: "Причина",
  // Опубликованную карточку менеджер меняет правкой на модерацию (как вендор из кабинета)
  moderatedNotice:
    "Витрина опубликована: название и описания вы меняете через модерацию, услуги — тоже (их правки ждут решения модератора). Клиенты видят прежнее, пока модератор не решит. Остальные поля сохраняются сразу.",
  moderatedHint: "Через модерацию",
  sentForModeration: (fields: string, rest: boolean) =>
    `Отправлено на модерацию: ${fields}. В карточке появится после решения модератора.${rest ? " Остальное сохранено." : ""}`,
  pendingRevisionTitle: "Правка ждёт решения модератора",
  pendingRevisionOpen: "Открыть правку",

  actions: {
    submit: "Отправить на проверку",
    publish: "Опубликовать",
    suspend: "Приостановить",
    reject: "Отклонить",
    draft: "Вернуть в черновик",
  },
  actionHints: {
    publish: "Готовые фото карточки, ещё ждущие решения, будут одобрены.",
    suspend: "Карточка пропадёт из каталога. Причину увидит вендор.",
    reject: "Причину увидит вендор.",
    draft: "Комментарий попадёт в историю статусов.",
    submit: "Комментарий попадёт в историю статусов.",
  },
  reason: "Причина",
  comment: "Комментарий",
  confirm: "Подтвердить",

  // фото
  photos: "Фото",
  photosHint: (min: number, max: number) =>
    `Минимум ${min}, максимум ${max}. Первое — обложка. Фото сжимаются в браузере, метаданные (в том числе геопозиция) удаляются.`,
  noFacesWarning:
    "На фото не должно быть людей и лиц — только то, что предлагает витрина: зал, машины, цветы, торты, подарки, оформление. Фото с людьми не загружайте.",
  noFacesAck: "Подтверждаю: на выбранных фото нет лиц",
  // Портфолио (фото и видео, студия): люди на фото — только с их согласия
  portfolioWarning:
    "Портфолио: люди на фото допустимы, только если они согласны на публикацию. Нет согласия — загружайте только фото без лиц.",
  photoAckLabel: "Что на выбранных фото",
  photoAckConsent: "Люди на фото согласны на публикацию",
  photoAckNoFaces: "На фото нет лиц",
  addPhotos: "Выбрать фото",
  photosDrop: "JPEG, PNG, WebP или HEIC — можно перетащить сюда",
  photosEmpty: "Фото ещё нет.",
  uploading: (done: number, total: number) => `Загружаем ${done} из ${total}…`,
  cover: "Обложка",
  makeCover: "Сделать обложкой",
  moveLeft: "Раньше",
  moveRight: "Позже",
  moveEarlier: (n: number) => `Фото ${n}: раньше`,
  moveLater: (n: number) => `Фото ${n}: позже`,
  photoN: (n: number) => `Фото ${n}`,
  addPhotosPhone: "Снять или выбрать фото",
  photosPick: "Камера или галерея: JPEG, PNG, WebP, HEIC",
  deletePhoto: "Удалить",
  deletePhotoTitle: "Удалить фото?",
  deletePhotoHint: "Фото пропадёт из карточки. Вернуть его можно, только загрузив заново.",
  approve: "Одобрить",
  decline: "Отклонить",
  moderationStates: { pending: "Ждёт решения", approved: "Одобрено", declined: "Отклонено" },
  imageErrors: {
    empty: "пустой файл",
    too_large: "слишком большой файл",
    unsupported_format: "не фото или формат не поддерживается (нужны JPEG, PNG, WebP)",
    corrupt: "файл повреждён",
    animated: "анимация не подходит",
    metadata_present: "в файле остались метаданные",
    dimensions_too_large: "слишком большое разрешение",
    dimensions_too_small: "слишком маленькое фото (короткая сторона от 320 px)",
    decode_failed: "браузер не смог открыть файл (HEIC? сохраните как JPEG)",
    encode_failed: "браузер не смог подготовить фото",
  } as Record<string, string>,
  photoFailed: (name: string, why: string) => `${name}: ${why}`,

  // занятость
  availability: "Занятые дни",
  availabilityHint: "Отметьте дни, когда зал занят. Нажмите на день, чтобы отметить или снять.",
  availabilityReadOnly: "Дни, когда зал занят. Отмечают вендор, менеджер и администратор.",
  prevMonth: "Предыдущий месяц",
  nextMonth: "Следующий месяц",
  busy: "занят",
  rangeMode: "Несколько дней",
  rangePickStart: "Нажмите на первый день.",
  rangePickEnd: "Теперь — на последний день.",
  rangeChosen: (n: number) => `Выбрано дней: ${n}.`,
  rangeInside: "в выборе",
  rangeBusy: (n: number) => `Занять (${n})`,
  rangeFree: "Освободить",
  legend: "Обозначения",
  legendFree: "свободно",
  legendBusy: "занято",
  legendToday: "сегодня",
  legendChosen: "в выборе",
  busySources: {
    vendor: "отметил вендор",
    staff: "отметил сотрудник",
    request_decline: "отказ по заявке",
  } as Record<string, string>,
  weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],

  // модерация
  moderationEmpty: "Очередь пуста: на проверке ничего нет.",
  submittedAt: "Отправлена",
  photosCount: (ready: number, approved: number) => `фото: ${ready}, одобрено: ${approved}`,
  listingsInReview: "Карточки на проверке",
  revisions: "Правки опубликованных карточек",
  revisionsHint:
    "Название, описания, данные витрины и видео опубликованной карточки вендор из кабинета меняет только через правку, менеджер из панели — название и описания: клиент видит одобренную версию, пока правка ждёт решения.",
  revisionsEmpty: "Правок, ждущих решения, нет.",
  revisionFields: {
    name: "Название",
    priceFromUzs: "Цена от",
    priceUnit: "За что",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    packages: "Пакеты",
    attributes: "Данные витрины",
    videoLinks: "Видео",
  } as Record<string, string>,
  revisionStatus: {
    pending: "Ждёт решения",
    approved: "Одобрена",
    declined: "Отклонена",
    withdrawn: "Отозвана вендором",
  } as Record<string, string>,
  revisionStale:
    "Карточку меняли после того, как начали правку. Сравните «сейчас» и «предлагает» внимательно.",
  revisionInvalid: "Правка не проходит проверку полей (например, цена не числом). Её можно только отклонить.",
  revisionField: "Поле",
  revisionNow: "Сейчас",
  revisionProposed: { partner: "Предлагает вендор", staff: "Предлагает сотрудник" },
  // Кто предложил правку: вендор из кабинета или сотрудник (менеджер) из панели
  proposedBy: (kind: "partner" | "staff", name: string | null) =>
    kind === "partner" ? "Предложил вендор из кабинета" : `Предложил сотрудник${name ? ` · ${name}` : ""}`,
  revisionApprove: "Одобрить и применить",
  revisionApproveHint: "Новые значения сразу появятся в опубликованной карточке.",
  revisionDecline: "Отклонить",
  revisionDeclineHint: "Причину увидит вендор.",
  revisionWhoDecides: "Правка ждёт решения: одобряет или отклоняет модератор или администратор.",
  revisionDecided: (status: string, by: string | null, at: string) =>
    `${status}${by ? ` · ${by}` : ""} · ${at}`,
  openListing: "К карточке",
  photoQueue: "Новые фото",
  photoQueueHint:
    "Фото, которые вендор или менеджер добавил в опубликованную карточку. Клиенты их не видят, пока фото не одобрят. Одобрить или отклонить — на странице карточки.",
  photoQueueEmpty: "Новых фото, ждущих решения, нет.",
  pendingPhotos: (n: number) => `ждут решения: ${n}`,

  // заявки
  requestsEmpty: "Заявок нет.",
  requestNo: (n: number) => `№ ${n}`,
  requestsCount: (n: number) => `заявок: ${n}`,
  sla: {
    waiting: "Ждёт ответа",
    overdue: "Просрочена",
    breached: "Нарушен срок",
    answered: "Ответ в срок",
    answered_late: "Ответ с опозданием",
    ops_contacted: "Связались мы",
    closed: "Закрыта",
  } as Record<string, string>,
  slaLate: "Требуют действия",
  requestStatus: {
    new: "Новая",
    viewed: "Просмотрена",
    contacted: "Вендор связался",
    deal: "Договорились",
    declined: "Отказ вендора",
    withdrawn: "Отозвана клиентом",
    expired: "Истекла",
  } as Record<string, string>,
  declineReasons: {
    busy: "Занято",
    format: "Не наш формат",
    price: "Не сошлись в цене",
    other: "Другое",
  } as Record<string, string>,
  requestsSearch: "Номер, зал, вендор",
  colRequest: "Заявка",
  colEvent: "Событие",
  colDue: "Срок ответа",
  guests: (n: number | null) => (n === null ? "гости не указаны" : `${n} гостей`),
  dueIn: "до",
  requestClient: "Клиент",
  requestComment: "Комментарий",
  requestBudget: "Бюджет",
  contactPurged: "Контакты клиента удалены по сроку хранения.",
  clientPhone: "Телефон клиента",
  clientPhoneHint: "Только администратор и только с причиной. Просмотр пишется в журнал.",
  clientPhoneReason: "Зачем нужен номер",
  vendorPhones: "Кому звонить у вендора",
  listingPhone: "Телефон карточки",
  firstResponse: "Первый ответ",
  firstViewed: "Просмотрена вендором",
  source: "Источник",
  reminders: (n: number) => `напоминаний: ${n}`,

  // работа с заявкой
  requestActions: "Работа с заявкой",
  remindVendor: "Напомнить вендору",
  remindHint:
    "Сообщение в Telegram всем, кто вошёл в кабинет вендора. Между напоминаниями — пауза из настроек.",
  remindUnreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните.",
  remindAgainAt: (at: string) => `Следующее напоминание — после ${at}`,
  remindSent: "Напоминание отправлено",
  markContacted: "Связались",
  markContactedHint:
    "Отметка оператора: связь с клиентом состоялась. В ответы вендора она не засчитывается; клиенту уйдёт то же сообщение, что при ответе зала.",
  notAwaiting: "Заявка уже не ждёт первого ответа вендора.",
  timeline: "Срок ответа по шагам",
  timelineEvents: {
    created: "Заявка создана",
    viewed: "Вендор открыл заявку",
    due: "Срок ответа",
    dueFuture: "Срок ответа истекает",
    breached: "Срок нарушен: клиенту предложены похожие, команде — оповещение",
    response: "Первый ответ",
  },
  reminderAuto: (stage: number | null) => `Напоминание вендору (авто${stage ? `, этап ${stage}` : ""})`,
  reminderOps: (by: string | null) => `Напоминание от команды${by ? ` · ${by}` : ""}`,
  reminderDelivery: (recipients: number, delivered: number, failed: number) =>
    `получателей: ${recipients}, доставлено: ${delivered}${failed ? `, не доставлено: ${failed}` : ""}`,
  notes: "Заметки команды",
  notesHint: "Видны только сотрудникам. Добавить можно, изменить и удалить — нет. Без телефонов клиента.",
  notesEmpty: "Заметок нет.",
  noteText: "Новая заметка",
  addNote: "Добавить заметку",

  // клиенты
  clientsSearch: "Номер заявки или код клиента (C-…)",
  clientsSearchHint: "По имени и телефону не ищем.",
  clientsEmpty: "Клиентов не нашлось.",
  onlyBlocked: "Только заблокированные",
  colClient: "Клиент",
  colSince: "С нами с",
  colLastSeen: "Был в приложении",
  colRequests: "Заявки",
  colState: "Состояние",
  clientBlocked: "Заблокирован",
  clientDeleted: "Удалил аккаунт",
  clientActive: "Активен",
  clientProfile: "Профиль",
  clientName: "Имя в Telegram",
  clientUsername: "Имя пользователя",
  clientLocale: "Язык",
  clientCanMessage: "Бот может писать",
  clientDeletedNote: "Клиент удалил аккаунт: имени и телефона больше нет, заявки и журналы остались.",
  yes: "да",
  no: "нет",
  locales: { ru: "русский", uz: "узбекский" } as Record<string, string>,
  clientRequests: "Заявки клиента",
  clientConsents: "Журнал согласий",
  consentsEmpty: "Согласий нет.",
  consentPurposes: {
    client_service: "Аккаунт клиента",
    request_transfer: "Передача контактов вендору",
    bot_notifications: "Уведомления в боте",
    vendor_contact: "Данные контактного лица",
    vendor_phone_public: "Публикация телефона",
    vendor_offer: "Оферта",
  } as Record<string, string>,
  consentActions: { grant: "дал", withdraw: "отозвал" } as Record<string, string>,
  consentVersion: (v: number) => `версия текста ${v}`,
  blockTitle: "Блокировка",
  blockHint:
    "Заблокированный клиент не входит в приложение и не создаёт заявок. Причина обязательна; блокировка — в журнале.",
  block: "Заблокировать",
  unblock: "Снять блокировку",
  unblockHint: "Клиент снова сможет входить в приложение и отправлять заявки. Снятие — в журнале.",
  blockedSince: (at: string, by: string | null) => `Заблокирован ${at}${by ? ` · ${by}` : ""}`,
  clientPhoneProfile: "Телефон из профиля",

  // уведомления
  outboxCounts: {
    pending: "Ждут отправки",
    sending: "Отправляются",
    failed: "Повтор после сбоя",
    dead: "Не доставлены",
    sent: "Отправлено за сутки",
  } as Record<string, string>,
  outboxOldest: (at: string) => `Самое давнее ожидающее — с ${at}. Если давно, отправитель не работает.`,
  outboxDead: "Не доставлены",
  outboxDeadHint:
    "Бот не смог отправить сообщение: получатель заблокировал бота, не привязан или Telegram не ответил. Повтор ставит сообщение в очередь заново.",
  outboxDeadEmpty: "Всё доставлено.",
  retryNotice: (kind: string) => `Повторить: ${kind}`,
  outboxShown: (shown: number, total: number) => `Показаны последние ${shown} из ${total}.`,
  colKind: "Вид",
  colRecipient: "Получатель",
  colAttempts: "Попыток",
  colError: "Причина",
  colWhen: "Когда",
  recipientKinds: {
    client: "клиент",
    vendor_user: "вендор",
    staff: "сотрудник",
    system: "система",
  } as Record<string, string>,
  noticeKinds: {
    "vendor.request_new": "Вендору: новая заявка",
    "vendor.sla_reminder": "Вендору: напоминание (авто)",
    "vendor.ops_reminder": "Вендору: напоминание от команды",
    "client.request_status": "Клиенту: статус заявки",
    "client.sla_breach": "Клиенту: вендор молчит — похожие",
    "ops.sla_breach": "Команде: просрочка",
    "ops.outbox_dead": "Команде: не доставлено",
    "ops.revision_submitted": "Команде: правка карточки",
    "ops.daily_digest": "Команде: утренняя сводка",
    "ops.weekly_report": "Команде: отчёт за неделю",
    "ops.api_error": "Команде: ошибки сервера",
  } as Record<string, string>,

  // журнал
  auditTabs: { actions: "Действия", pii: "Просмотры телефонов" },
  auditActor: "Сотрудник",
  auditActorAny: "Любой",
  auditActorKind: "Кто",
  auditType: "Объект",
  auditTypeAny: "Любой",
  auditObject: "id объекта",
  auditAction: "Действие (начало кода)",
  auditFrom: "С",
  auditTo: "По",
  auditAnyDate: "любая дата",
  auditNoDate: "Без даты",
  auditApply: "Показать",
  auditReset: "Сбросить",
  auditEmpty: "Записей нет.",
  auditPrev: "Новее",
  auditNext: "Старше",
  colActor: "Кто",
  colAction: "Действие",
  colObject: "Объект",
  colDetail: "Подробности",
  colPurpose: "Зачем",
  auditTypes: {
    vendor: "Вендор",
    vendor_user: "Пользователь кабинета",
    listing: "Карточка",
    request: "Заявка",
    client: "Клиент",
    staff: "Сотрудник",
    setting: "Настройка",
    outbox: "Уведомление",
    maintenance: "Обслуживание",
  } as Record<string, string>,
  piiSubjects: {
    client: "Клиент (профиль)",
    request_contact: "Клиент (заявка)",
    vendor_contact: "Контакт вендора",
    vendor_user: "Пользователь кабинета",
    listing_contact: "Телефон карточки",
  } as Record<string, string>,
  auditActions: {
    "listing.create": "Карточка создана",
    "listing.update": "Карточка изменена",
    "listing_package.create": "Пакет добавлен",
    "listing_package.update": "Пакет изменён",
    "listing_package.delete": "Пакет удалён",
    "listing_contact.create": "Телефон карточки вписан",
    "listing_contact.update": "Телефон карточки изменён",
    "listing_contact.delete": "Телефон карточки убран",
    "listing_revision.update": "Решение по правке",
    "photo.create": "Фото загружено",
    "photo.update": "Фото изменено",
    "availability.create": "День отмечен занятым",
    "availability.delete": "День освобождён",
    "vendor.create": "Вендор создан",
    "vendor.update": "Вендор изменён",
    "vendor_contact.create": "Контакты вендора вписаны",
    "vendor_contact.update": "Контакты вендора изменены",
    "vendor_user.create": "Пользователь кабинета заведён",
    "vendor_user.update": "Пользователь кабинета изменён",
    "vendor_user.telegram_claim": "Вендор привязал Telegram",
    "request.update": "Заявка изменена сотрудником",
    "request.remind": "Напоминание вендору",
    "request_note.create": "Заметка к заявке",
    "client.block": "Клиент заблокирован",
    "client.unblock": "Блокировка снята",
    "client.delete_account": "Клиент удалил аккаунт",
    "outbox.retry": "Повтор уведомления",
    "settings.update": "Настройка изменена",
    "staff.invite": "Сотрудник приглашён",
    "staff.role": "Роль изменена",
    "staff.deactivate": "Сотрудник отключён",
    "staff.activate": "Сотрудник включён",
    "staff.telegram_claim": "Приглашение принято",
    "maintenance.daily": "Ежедневное обслуживание",
  } as Record<string, string>,
  piiPurposes: {
    staff_reveal: "показать сотруднику",
    staff_vendor_contact: "звонок вендору",
    staff_vendor_user: "пользователь кабинета",
    staff_listing: "телефон карточки",
    request_inbox: "вендор в кабинете",
    self: "сам себе",
    system_notification: "уведомление",
  } as Record<string, string>,

  // команда
  inviteTitle: "Пригласить сотрудника",
  inviteHint:
    "Сотрудник войдёт через Telegram: имя пользователя должно совпадать с его именем в Telegram. При первом входе приглашение привяжется к его аккаунту.",
  inviteHintPhone:
    "Сотрудник войдёт на сайте Bayramm по коду на этот номер — при первом входе приглашение привяжется к его аккаунту. Если номер уже подтверждён в аккаунте Bayramm, приглашение примется сразу. Номер не хранится: только его отпечаток.",
  inviteHintPhoneOff:
    "Вход по коду на телефон в этом окружении пока выключен: приглашение примется, когда сотрудник подтвердит номер в аккаунте Bayramm. Номер не хранится: только его отпечаток.",
  inviteBy: "Как войдёт",
  inviteByTelegram: "По имени в Telegram",
  inviteByPhone: "По номеру телефона",
  inviteName: "Имя для панели",
  inviteUsername: "Имя пользователя Telegram",
  invitePhone: "Номер телефона",
  inviteRole: "Роль",
  invite: "Пригласить",
  invited: "Приглашение создано",
  invitedByPhone: "по телефону",
  colName: "Сотрудник",
  colRole: "Роль",
  colStatus: "Статус",
  you: "это вы",
  memberActive: "Действует",
  memberInactive: "Отключён",
  memberPending: "Ещё не входил",
  memberAccepted: "Приглашение принято",
  memberLinked: (at: string) => `Вошёл через Telegram ${at}`,
  changeRole: "Сменить роль",
  deactivate: "Отключить",
  activate: "Включить",
  deactivateHint: "Сотрудник сразу потеряет доступ: его сессии будут отозваны.",
  activateHint: "Сотрудник снова сможет входить в панель — с той же ролью.",
  roleHints: {
    admin: "Всё, включая команду, настройки, журнал и телефоны клиентов",
    manager: "Вендоры и карточки, заявки и клиенты; не публикует",
    moderator: "Проверка и публикация карточек, фото и правок",
  } as Record<string, string>,

  // настройки
  settingsLabels: {
    sla_hours: "Срок ответа вендора, часов",
    sla_reminder_hours: "Напоминания вендору через, часов",
    quiet_hours: "Тихие часы (по Ташкенту)",
    ops_reminder_pause_minutes: "Пауза между напоминаниями от команды, минут",
    min_photos: "Минимум фото для публикации",
    max_photos: "Максимум фото в карточке",
    client_requests_per_day: "Заявок клиента за сутки",
    request_contact_retention_days: "Хранить контакты из заявки, дней после события",
    session_retention_days: "Хранить истёкшие сессии, дней",
    otp_retention_hours: "Хранить коды входа, часов",
  } as Record<string, string>,
  settingsHints: {
    sla_hours:
      "1–72. Действует на новые заявки: у созданной срок уже зафиксирован. Напоминания — раньше срока.",
    sla_reminder_hours:
      "До двух, по возрастанию, каждое 1–72 и раньше срока ответа. Пусто — без напоминаний.",
    quiet_hours: "Ночью напоминания ждут утра. Начало и конец — ЧЧ:ММ.",
    ops_reminder_pause_minutes:
      "5–1440. Кнопка «Напомнить» на заявке снова доступна через столько минут после прошлого напоминания.",
    min_photos: "3–10: меньше трёх нельзя — правило продукта. Не больше максимума.",
    max_photos: "3–30, не меньше минимума.",
    client_requests_per_day: "1–100: защита вендоров от спама.",
    request_contact_retention_days: "1–3650. Потом имя, телефон и комментарий стираются.",
    session_retention_days: "1–365.",
    otp_retention_hours: "1–720.",
  } as Record<string, string>,
  settingInvalid: "Значение не подходит: проверьте границы и согласованность с другими настройками.",
  settingValue: "Значение",
  reminderFirst: "Первое",
  reminderSecond: "Второе",
  quietFrom: "С",
  quietTo: "До",
  updatedBy: (at: string, by: string | null) => `Изменено ${at}${by ? ` · ${by}` : ""}`,

  // метрики запуска
  metricsNow: "Сейчас",
  metricsQueues: {
    awaiting: "Ждут ответа площадки",
    overdue: "Из них срок вышел",
    deadTotal: "Не доставлено уведомлений",
    listingsReview: "Карточек на проверке",
    revisionsPending: "Правок ждут решения",
    photosPending: "Новых фото ждут решения",
  } as Record<string, string>,
  metricsWeekly: "По неделям",
  metricsWeeklyHint: (hours: number) =>
    `Неделя — с понедельника, по Ташкенту; заявка — в неделе, когда её отправили. «В срок» — площадка сама ответила за ${hours} ч: связались, договорились или отказ. Просмотр, звонок и «связались» от команды — не ответ площадки. Доля — от заявок, исход которых известен: площадка ответила в срок или срок уже прошёл; отозванные клиентом до срока без ответа — не в расчёте. Время ответа — по заявкам с ответом площадки.`,
  metricsVendors: "Вендоры за 30 дней",
  metricsVendorsHint:
    "Вендоры с заявками за 30 дней или с опубликованной площадкой. По умолчанию худшие по доле ответов в срок — сверху: им стоит позвонить.",
  metricsVendorsEmpty: "Пока нет ни заявок, ни опубликованных площадок.",
  colWeek: "Неделя",
  colAnswered: "Ответ в срок",
  colResponseTime: "Время ответа",
  colMedian: "Медиана ответа",
  colAgreed: "Договорились",
  colBreaches: "Срок сорван",
  colDead: "Не доставлено",
  colLastRequest: "Последняя заявка",
  weekNow: "идёт",
  clientsCount: (n: number) => `клиентов: ${n}`,
  answeredOf: (answered: number, measurable: number) => `${answered} из ${measurable}`,
  medianTime: (median: string) => `медиана ${median}`,
  p90Time: (p90: string) => `у 90% — до ${p90}`,
  sortAsc: "по возрастанию",
  sortDesc: "по убыванию",
  // Сортировка вендоров на телефоне: столбец и направление одним выбором
  sortRateAsc: "Меньше ответов в срок — сверху",
  sortRateDesc: "Больше ответов в срок — сверху",
  sortRequestsDesc: "Больше заявок — сверху",
  sortMedianDesc: "Дольше отвечают — сверху",
  vendorResponse: "Ответы на заявки",
  vendorResponseHint:
    "За 30 дней. «В срок» — площадка сама ответила за срок заявки; «связались» от команды не считается.",
  vendorResponseEmpty: "За 30 дней заявок не было.",
  activeListings: (n: number) => `опубликовано площадок: ${n}`,

  // ── категории, витрины, услуги (v0.2) ──
  colCategory: "Категория",
  allCategories: "Все категории",
  categoryFirst: "Категория витрины",
  categoryFirstHint: "С ней заведётся первая витрина. Другие — потом, на странице вендора.",
  categoryRequired: "Выберите категорию",
  vitrinasHint:
    "Витрина — страница вендора в одной категории: свои данные, услуги, фото, занятость и заявки. Вход в кабинет, контакты и проверка — общие у вендора.",
  addVitrina: "Добавить витрину в другой категории",
  addVitrinaLead:
    "Новая витрина появится черновиком: дальше — данные витрины, услуги и фото на её странице. Категорию партнёр не меняет.",
  vitrinaHas: (names: string) => `Уже есть: ${names}`,
  vitrinaName: "Название витрины",
  vitrinaNameHint: "Пусто — название вендора",
  createVitrina: "Создать витрину",
  categoryChange: "Сменить категорию",
  categoryChangeHint:
    "Только пока у витрины нет заявок и услуг: данные витрины очистятся. Если категория другая по сути — лучше новая витрина.",
  categoryChangeLocked:
    "У витрины есть услуги — категорию не сменить. Заведите вендору новую витрину в нужной категории.",
  categoryNew: "Новая категория",
  required: "обязательно",
  priceFromAuto: "Цена «от» — из услуг",
  priceFromNone: "появится с первой услугой с ценой",
  listingDataSections: {
    attributes: "Данные витрины",
    attributesHint: (category: string) =>
      `Поля категории «${category}»: по ним клиент фильтрует каталог. Обязательные нужны для публикации.`,
    capacity: "Вместимость",
    capacityHint: "Для площадки — сколько гостей принимает зал.",
    occupancy: "Заказов одновременно",
    occupancyHint:
      "Сколько машин, экипажей или команд работают в одно время. Часть дня занята, когда договорённостей на неё столько же.",
    videos: "Видео",
    videosHint: (n: number) =>
      `До ${n} ссылок на ролики YouTube или посты Instagram. Файлы видео не загружаются.`,
  },
  attributeError: "Проверьте значение",
  attributeIntError: (min: number, max: number) => `Целое число от ${min} до ${max}`,
  listAdd: "Добавить",
  listRemove: "Убрать",
  listItem: (label: string, n: number) => `${label}, № ${n}`,
  listEmpty: "Пока пусто.",
  listLimit: (n: number) => `До ${n} записей`,
  videoLink: (n: number) => `Ссылка ${n}`,
  videoAdd: "Добавить ссылку",
  videoRemove: "Убрать ссылку",
  videoLinkError: "Нужна ссылка на ролик YouTube или пост Instagram",
  parallelCapacityError: "Целое число от 1 до 50",
  readiness: "Готовность к публикации",
  readinessReady: "Всё нужное для публикации есть",
  readinessAttributes: (labels: string) => `Не заполнено: ${labels}`,
  readinessServices: (labels: string) => `Нужны услуги: ${labels}`,
  readinessPhotos: (n: number, min: number) => `Фото: ${n} из ${min}`,

  // услуги витрины
  services: "Услуги",
  servicesHint:
    "Цены витрины — только в услугах: «по запросу» не бывает. Цена «от» в каталоге — из одобренных услуг.",
  servicesEmpty: "Услуг пока нет.",
  servicesDecides: "Вы решаете по модерации: ваши услуги и правки сразу на витрине.",
  servicesManager:
    "Новые услуги и правки опубликованной витрины уходят модератору; у неопубликованной их одобрит публикация.",
  serviceStatus: {
    draft: "Черновик",
    review: "На проверке",
    active: "На витрине",
    rejected: "Отклонена",
    paused: "Снята",
  } as Record<string, string>,
  serviceProposal: "Правка ждёт решения",
  serviceDeclined: (reason: string) => `Отклонена: ${reason}`,
  serviceProposalDeclined: (reason: string) => `Правку отклонили: ${reason}`,
  serviceMin: (n: number, unit: string) => `минимум ${n}, ${unit}`,
  serviceLead: (n: number) => `заказ за ${n} дн.`,
  serviceNew: "Новая услуга",
  serviceAdd: "Добавить услугу",
  serviceAddFrom: "Услуга из каталога категории",
  serviceEdit: "Изменить",
  serviceEditTitle: (name: string) => `Услуга: ${name}`,
  serviceSave: "Сохранить услугу",
  serviceCreate: "Добавить услугу",
  servicePause: "Снять с витрины",
  serviceResume: "Вернуть на витрину",
  serviceSubmit: "Отправить на проверку",
  serviceDelete: "Удалить услугу",
  serviceDeleteTitle: "Удалить услугу?",
  serviceDeleteHint: "Услуга пропадёт из витрины. Заявки, где её выбрали, сохранят её как была.",
  serviceFields: {
    type: "Услуга",
    nameRu: "Название (RU)",
    nameUz: "Nomi (UZ)",
    priceUzs: "Цена, сум",
    priceUnit: "За что",
    minQty: "Минимальный заказ",
    minQtyHint: "Например, от 3 часов или от 50 штук. Пусто — без минимума",
    leadDays: "Заказ не позже чем за, дней",
    leadDaysHint: "Пусто — как у витрины",
    includesRu: "Что входит (RU)",
    includesUz: "Nima kiradi (UZ)",
    name: "Название",
    includes: "Что входит",
    options: "Добавки",
  } as Record<string, string>,
  serviceErrors: {
    type: "Выберите услугу из каталога",
    name: "Название на двух языках, от 2 символов",
    priceUzs: "Целое число больше нуля",
    priceUnit: "Выберите единицу этой услуги",
    minQty: "Целое число от 1",
    leadDays: "От 0 до 365 дней",
    includes: "До 1000 символов на каждом языке",
    options: "Не больше 10 добавок, у каждой — название на двух языках и цена",
  } as Record<string, string>,
  optionsHint: "Платные добавки к услуге: клиент отмечает их в заявке, цену пишете вы.",
  optionAdd: "Своя добавка",
  optionFromCatalog: "Добавка из каталога",
  optionRemove: "Убрать",
  optionN: (n: number) => `Добавка ${n}`,
  optionError: "Название на двух языках и цена больше нуля",

  // очередь услуг в модерации
  serviceQueue: "Услуги и их правки",
  serviceQueueHint:
    "Новые услуги и правки услуг опубликованных витрин. Клиент видит одобренное, пока здесь не решат. Услуги неопубликованной витрины одобряет её публикация.",
  serviceQueueEmpty: "Услуг, ждущих решения, нет.",
  serviceQueueKinds: { review: "Новая услуга", proposal: "Правка услуги" } as Record<string, string>,
  serviceNow: "Сейчас",
  serviceProposed: "Предлагают",
  serviceApprove: "Одобрить",
  serviceDecline: "Отклонить",
  serviceDeclineHint: "Причину увидит партнёр в кабинете.",
  serviceApproveHint: "Услуга или правка сразу появится на витрине.",

  // занятость по режимам категорий
  availabilityHints: {
    day: "Отметьте дни, когда витрина занята. Нажмите на день, чтобы отметить или снять.",
    parts:
      "День делится на утро, день и вечер. Нажмите на день, чтобы отметить его целиком или по частям. Часть занята, когда отмечена или договорённостей на неё столько же, сколько заказов одновременно.",
    slot: "Студия: отмечайте дни целиком. Время начала и часы съёмки приходят в заявке.",
  },
  dayParts: { morning: "Утро", day: "День", evening: "Вечер" } as Record<string, string>,
  wholeDay: "Весь день",
  markBusy: "Занять",
  partState: { free: "свободно", busy: "занято", full: "все места заняты" } as Record<string, string>,
  partBookings: (count: number, capacity: number) => `договорённостей: ${count} из ${capacity}`,
  dayLoad: { free: "свободно", partial: "занято частично", busy: "занято" } as Record<string, string>,
  legendPartial: "занято частично",
  capacityNow: (n: number) => `Заказов одновременно: ${n} — меняется в данных витрины.`,
  pickedDay: (day: string) => `День: ${day}`,
  leadTitle: "Срок заказа",
  leadHint: "Календаря у этой категории нет: витрина принимает заказы не позже чем за указанный срок.",
  leadDaysValue: (n: number) => `Заказ не позже чем за ${n} дн.`,
  leadNotSet: "Срок не указан — заполните «Заказ не позже чем за, дней» в данных витрины.",
  leadServices: (list: string) => `Свой срок у услуг: ${list}`,

  // заявки по категориям
  dayPart: "Часть дня",
  requestDetails: "Что нужно клиенту",
  requestServices: "Выбранные услуги",
} as const;

/** Текст ошибки API по коду */
export function apiErrorText(code: string): string {
  return t.api[code] ?? t.api.unknown ?? "";
}
