/* Тексты панели оператора. Панель только на русском: ею пользуется команда, не клиенты.
   Узбекские здесь — только подписи полей, куда вписывают текст для клиентов на узбекском. */
export const t = {
  area: "панель оператора",
  skip: "К содержимому",
  sections: "Разделы панели",
  vendors: "Вендоры",
  vendorsLead: "Карточки вендоров: создание, правка, отметка о проверке.",
  moderation: "Модерация",
  moderationLead: "Карточки и фото, которые ждут проверки перед публикацией.",
  requests: "Заявки",
  requestsLead: "Заявки клиентов и ответы вендоров. Без ответа дольше 12 часов — вверху.",
  clients: "Клиенты",
  clientsLead:
    "Клиенты — под псевдонимом: поиск по номеру заявки или коду клиента. Выгрузки базы клиентов нет.",
  notifications: "Уведомления",
  notificationsLead: "Очередь сообщений бота: сколько ждёт отправки и что не доставлено.",
  audit: "Журнал",
  auditLead: "Кто, что и когда сделал в панели, и кто смотрел телефоны. Только чтение.",
  team: "Команда",
  teamLead: "Сотрудники панели: приглашение по имени в Telegram, роли, отключение.",
  settings: "Настройки",
  settingsLead: "Срок ответа, напоминания, фото, лимиты и сроки хранения. Каждое изменение — в журнале.",
  noAccess: "У вашей роли нет доступа к этому разделу.",
  soon: "Раздел в разработке",
  notFound: "Страница не найдена",
  notFoundLead: "Проверьте адрес или откройте список вендоров.",
  toHome: "К вендорам",

  // вход
  login: "Вход для сотрудников",
  loginLead:
    "Войдите через Telegram. Доступ открывает администратор — по приглашению на ваше имя пользователя.",
  loginChecking: "Проверяем вход…",
  loginWidgetFailed: "Кнопка входа Telegram не загрузилась. Проверьте соединение и попробуйте ещё раз.",
  loginBotLoading: "Загружаем кнопку входа…",
  loginBotFailed: "Не удалось получить настройки входа. Проверьте соединение и попробуйте ещё раз.",
  retry: "Повторить",
  signOut: "Выйти",
  signedInAs: "Вы вошли как",
  errors: {
    invalid: "Telegram не подтвердил вход или подтверждение устарело. Войдите ещё раз.",
    denied:
      "Нет доступа к панели. Если вас пригласили, проверьте имя пользователя в Telegram или обратитесь к администратору.",
    unavailable: "Сервер не отвечает. Попробуйте ещё раз через минуту.",
  },
  roles: {
    admin: "Администратор",
    manager: "Менеджер",
    moderator: "Модератор",
  },

  // заголовки экранов внутри разделов
  views: {
    vendorNew: "Новый вендор",
    vendor: "Вендор",
    listingNew: "Новая карточка",
    listing: "Карточка",
    request: "Заявка",
    client: "Клиент",
    revision: "Правка карточки",
  },

  // общее
  loading: "Загружаем…",
  save: "Сохранить",
  saving: "Сохраняем…",
  saved: "Сохранено",
  cancel: "Отмена",
  back: "Назад",
  search: "Поиск",
  all: "Все",
  none: "—",
  show: "Показать",
  hidden: "скрыт",
  notSet: "не указан",
  more: "Ещё",
  optional: "по желанию",
  total: (n: number) => `Всего: ${n}`,
  // Коды ошибок API → понятный текст. Неизвестный код — общий текст
  api: {
    network: "Нет связи с сервером. Проверьте соединение и попробуйте ещё раз.",
    unknown: "Что-то пошло не так. Попробуйте ещё раз.",
    internal_error: "Ошибка на сервере. Попробуйте ещё раз через минуту.",
    service_unavailable: "Сервер временно недоступен. Попробуйте через минуту.",
    forbidden: "Для этого действия у вашей роли нет прав.",
    not_found: "Не найдено: возможно, запись удалили или адрес неверный.",
    invalid_input: "Проверьте выделенные поля.",
    invalid_request: "Запрос не принят. Обновите страницу и попробуйте ещё раз.",
    payload_too_large: "Слишком большой файл или текст.",
    version_conflict: "Карточку только что изменили. Обновите страницу — ваши правки не сохранены.",
    illegal_transition: "Из текущего статуса так нельзя. Обновите страницу.",
    publish_blocked: "Не хватает данных — список ниже.",
    reason_required: "Нужна причина.",
    slug_taken: "Этот адрес карточки уже занят — выберите другой.",
    stir_taken: "Этот СТИР уже у другого вендора.",
    phone_taken: "Этот номер уже заведён для входа — у этого или другого вендора.",
    duplicate_package: "Два пакета одного вида. Оставьте один.",
    user_linked: "Пользователь уже привязал Telegram — номер не сменить. Отключите его и заведите нового.",
    stir_missing: "Сначала впишите СТИР в реквизиты.",
    consent_text_missing: "Нет действующего текста согласия на обработку ПДн. Обратитесь к администратору.",
    checklist_locked: "Отметку не снять, пока карточки вендора опубликованы — сначала приостановите их.",
    too_many_photos: "Больше фото не добавить — достигнут предел.",
    duplicate_photo: "Это фото уже загружено.",
    invalid_image: "Фото не принято.",
    no_faces_ack_required: "Подтвердите, что на фото нет лиц.",
    storage_unavailable: "Хранилище фото недоступно. Попробуйте позже.",
    forbidden_for_actor: "Это действие недоступно.",
    moderated_field_requires_revision: "Поле меняется только через модерацию.",
    reminder_too_soon: "Вендору уже напоминали меньше 30 минут назад. Попробуйте позже или позвоните.",
    request_not_awaiting: "Заявка уже не ждёт ответа вендора.",
    vendor_unreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните вендору.",
    staff_self: "Себя нельзя отключить или сменить себе роль.",
    staff_last_admin: "Должен остаться хотя бы один действующий администратор.",
    username_taken: "Это имя в Telegram уже у действующего сотрудника.",
    revision_invalid: "Правка не проходит проверку полей — её можно только отклонить.",
    client_blocked: "Клиент заблокирован.",
  } as Record<string, string>,

  // статусы карточки
  status: {
    lead: "Лид",
    draft: "Черновик",
    review: "На проверке",
    active: "Опубликована",
    suspended: "Приостановлена",
    rejected: "Отклонена",
  },
  // Чего не хватает для проверки или публикации — коды app.listing_publish_blockers
  blockers: {
    price: "Цена «от»",
    capacity: "Вместимость (максимум гостей)",
    district: "Район",
    descriptions: "Описание на русском и узбекском",
    phone: "Телефон для заявок",
    packages: "Цены на будни и выходные",
    photos: "Фото: минимум 3 (для публикации — одобренные)",
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pd_consent: "Согласие на обработку ПДн подписано",
  } as Record<string, string>,
  blockersReview: "Не хватает для проверки",
  blockersActive: "Не хватает для публикации",
  readyToPublish: "Всё готово к публикации",
  legalForms: { ooo: "ООО", yatt: "ЯТТ (ИП)", self_employed: "Самозанятый" },
  priceUnits: { per_guest: "за гостя", per_event: "за мероприятие" },
  sum: "сум",

  // список вендоров
  newVendor: "Новый вендор",
  vendorsSearch: "Название, код, СТИР, телефон, контакт",
  vendorsEmpty: "Вендоров не нашлось.",
  vendorsEmptyAll: "Вендоров пока нет. Начните с «Новый вендор».",
  colVendor: "Вендор",
  colContact: "Контакт",
  colListings: "Карточки",
  colChecklist: "Проверка",
  colCabinet: "Кабинет",
  cabinetUsers: (users: number, linked: number) =>
    users === 0 ? "нет входа" : `${linked} из ${users} в Telegram`,
  noListings: "нет карточек",

  // вендор
  vendorCode: "Код",
  vendorSections: {
    business: "Бизнес",
    businessHint: "Название для панели и реквизиты. Скан документов не храним — только отметку о проверке.",
    contact: "Контакт",
    contactHint:
      "Контактное лицо вендора. Телефоны видны только по кнопке «Показать» — просмотр пишется в журнал.",
  },
  fields: {
    name: "Название",
    legalForm: "Форма",
    legalName: "Юрназвание",
    stir: "СТИР (9 цифр)",
    legalAddress: "Юрадрес",
    contractNo: "Номер договора",
    managerId: "Менеджер",
    contactPerson: "Контактное лицо",
    contactRole: "Должность",
    phone: "Телефон",
    phoneAlt: "Второй телефон",
    telegramUsername: "Telegram (@имя)",
  } as Record<string, string>,
  fieldErrors: {
    name: "От 2 до 120 символов",
    stir: "Ровно 9 цифр",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    phoneAlt: "Номер Узбекистана: +998 и 9 цифр",
    telegramUsername: "5–32 символа: латиница, цифры, _",
  } as Record<string, string>,
  phoneKeep: "Оставьте пустым, чтобы не менять",
  phoneNew: "Новый номер",
  createVendor: "Создать вендора",
  noManager: "Не назначен",

  checklist: "Проверка вендора",
  checklistHint: "Все четыре отметки нужны для публикации. Каждая отметка — в журнале действий.",
  checklistItems: {
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pdConsent: "Согласие на обработку ПДн подписано",
  },
  checkedBy: (by: string | null, at: string) => (by ? `${by}, ${at}` : at),
  phones: "Телефоны контакта",
  phoneMain: "Основной",
  phoneAlternative: "Второй",

  users: "Вход в кабинет",
  usersHint:
    "Заведите пользователя по номеру телефона. Вендор привяжет Telegram сам: откроет бота и поделится контактом с этого номера.",
  usersEmpty: "Пока никого нет.",
  addUser: "Добавить",
  userPhone: "Телефон для входа",
  userName: "Имя",
  telegramLinked: "Telegram привязан",
  telegramNotLinked: "Ждём привязки Telegram",
  userDisabled: "Отключён",
  disable: "Отключить",
  unlinkTelegram: "Отвязать Telegram",
  enable: "Включить",
  owner: "Владелец",
  member: "Сотрудник",

  listings: "Карточки",
  newListing: "Новая карточка",
  listingsEmpty: "У вендора пока нет карточек.",

  // карточка
  listingSections: {
    main: "Карточка",
    mainHint: "Название, адрес карточки и район. Адрес карточки (латиница) — в ссылке на неё.",
    texts: "Описание и адрес",
    textsHint: "На двух языках: клиент видит свой.",
    prices: "Цены и вместимость",
    pricesHint: "Цена обязательна: «по запросу» не бывает. Пакеты будней и выходных — обязательны для залов.",
    phone: "Телефон для заявок",
    phoneHint: "Клиент видит его сразу, до заявки.",
  },
  listingFields: {
    name: "Название",
    slug: "Адрес карточки",
    districtCode: "Район",
    addressRu: "Адрес (RU)",
    addressUz: "Manzil (UZ)",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    priceFromUzs: "Цена от, сум",
    priceUnit: "За что",
    capMin: "Гостей от",
    capMax: "Гостей до",
    phone: "Телефон",
    status: "Статус",
  } as Record<string, string>,
  listingFieldErrors: {
    name: "От 2 до 80 символов",
    slug: "Латиница, цифры и дефис, 3–40 символов",
    capMax: "Не меньше, чем «гостей от»",
    priceFromUzs: "Целое число больше нуля",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    packages: "Проверьте пакеты: у каждого названия на двух языках и цена",
  } as Record<string, string>,
  slugAuto: "Сформируется из названия",
  category: "Категория",
  packages: "Пакеты",
  packageKinds: { weekday: "Будни", weekend: "Выходные", custom: "Свой пакет" },
  packageDefaults: {
    weekday: { ru: "Будни", uz: "Ish kunlari" },
    weekend: { ru: "Выходные", uz: "Dam olish kunlari" },
  },
  packageNameRu: "Название (RU)",
  packageNameUz: "Nomi (UZ)",
  packagePrice: "Цена, сум",
  addPackage: "Добавить пакет",
  removePackage: "Убрать",
  createListing: "Создать карточку",
  startAs: "Создать как",
  phoneSet: "Телефон вписан",
  phoneMissing: "Телефона нет",
  phoneChange: "Сменить номер",
  history: "История статусов",
  historyEmpty: "Пока без изменений.",
  historyBy: { staff: "сотрудник", vendor_user: "вендор", system: "система", client: "клиент" } as Record<
    string,
    string
  >,
  openVendor: "К вендору",
  statusReason: "Причина",

  actions: {
    submit: "Отправить на проверку",
    publish: "Опубликовать",
    suspend: "Приостановить",
    reject: "Отклонить",
    draft: "Вернуть в черновик",
  },
  actionHints: {
    publish: "Готовые фото карточки, ещё ждущие решения, будут одобрены.",
    suspend: "Карточка пропадёт из каталога. Причину увидит вендор.",
    reject: "Причину увидит вендор.",
    draft: "Комментарий попадёт в историю статусов.",
    submit: "Комментарий попадёт в историю статусов.",
  },
  reason: "Причина",
  comment: "Комментарий",
  confirm: "Подтвердить",

  // фото
  photos: "Фото",
  photosHint: (min: number, max: number) =>
    `Минимум ${min}, максимум ${max}. Первое — обложка. Фото сжимаются в браузере, метаданные (в том числе геопозиция) удаляются.`,
  noFacesWarning:
    "На фото не должно быть людей и лиц — только зал, столы, оформление. Фото с людьми не загружайте.",
  noFacesAck: "Подтверждаю: на выбранных фото нет лиц",
  addPhotos: "Выбрать фото",
  photosEmpty: "Фото ещё нет.",
  uploading: (done: number, total: number) => `Загружаем ${done} из ${total}…`,
  cover: "Обложка",
  makeCover: "Сделать обложкой",
  moveLeft: "Раньше",
  moveRight: "Позже",
  deletePhoto: "Удалить",
  approve: "Одобрить",
  decline: "Отклонить",
  moderationStates: { pending: "Ждёт решения", approved: "Одобрено", declined: "Отклонено" },
  imageErrors: {
    empty: "пустой файл",
    too_large: "слишком большой файл",
    unsupported_format: "не фото или формат не поддерживается (нужны JPEG, PNG, WebP)",
    corrupt: "файл повреждён",
    animated: "анимация не подходит",
    metadata_present: "в файле остались метаданные",
    dimensions_too_large: "слишком большое разрешение",
    dimensions_too_small: "слишком маленькое фото (короткая сторона от 320 px)",
    decode_failed: "браузер не смог открыть файл (HEIC? сохраните как JPEG)",
    encode_failed: "браузер не смог подготовить фото",
  } as Record<string, string>,
  photoFailed: (name: string, why: string) => `${name}: ${why}`,

  // занятость
  availability: "Занятые дни",
  availabilityHint: "Отметьте дни, когда зал занят. Нажмите на день, чтобы отметить или снять.",
  prevMonth: "Предыдущий месяц",
  nextMonth: "Следующий месяц",
  busy: "занят",
  busySources: {
    vendor: "отметил вендор",
    staff: "отметил сотрудник",
    request_decline: "отказ по заявке",
  } as Record<string, string>,
  weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],

  // модерация
  moderationEmpty: "Очередь пуста: на проверке ничего нет.",
  submittedAt: "Отправлена",
  photosCount: (ready: number, approved: number) => `фото: ${ready}, одобрено: ${approved}`,
  listingsInReview: "Карточки на проверке",
  revisions: "Правки опубликованных карточек",
  revisionsHint:
    "Вендор меняет название, цену, описания и пакеты опубликованной карточки только через правку: клиент видит одобренную версию, пока правка ждёт решения.",
  revisionsEmpty: "Правок, ждущих решения, нет.",
  revisionFields: {
    name: "Название",
    priceFromUzs: "Цена от",
    priceUnit: "За что",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    packages: "Пакеты",
  } as Record<string, string>,
  revisionStatus: {
    pending: "Ждёт решения",
    approved: "Одобрена",
    declined: "Отклонена",
    withdrawn: "Отозвана вендором",
  } as Record<string, string>,
  revisionStale:
    "Карточку меняли после того, как вендор начал правку. Сравните «сейчас» и «предлагает» внимательно.",
  revisionInvalid: "Правка не проходит проверку полей (например, цена не числом). Её можно только отклонить.",
  revisionNow: "Сейчас",
  revisionProposed: "Предлагает вендор",
  revisionApprove: "Одобрить и применить",
  revisionApproveHint: "Новые значения сразу появятся в опубликованной карточке.",
  revisionDecline: "Отклонить",
  revisionDeclineHint: "Причину увидит вендор.",
  revisionDecided: (status: string, by: string | null, at: string) =>
    `${status}${by ? ` · ${by}` : ""} · ${at}`,
  openListing: "К карточке",

  // заявки
  requestsEmpty: "Заявок нет.",
  requestNo: (n: number) => `№ ${n}`,
  sla: {
    waiting: "Ждёт ответа",
    overdue: "Просрочена",
    breached: "Нарушен срок",
    answered: "Ответ в срок",
    answered_late: "Ответ с опозданием",
    ops_contacted: "Связались мы",
    closed: "Закрыта",
  } as Record<string, string>,
  slaLate: "Требуют действия",
  requestStatus: {
    new: "Новая",
    viewed: "Просмотрена",
    contacted: "Вендор связался",
    deal: "Договорились",
    declined: "Отказ вендора",
    withdrawn: "Отозвана клиентом",
    expired: "Истекла",
  } as Record<string, string>,
  declineReasons: {
    busy: "Занято",
    format: "Не наш формат",
    price: "Не сошлись в цене",
    other: "Другое",
  } as Record<string, string>,
  requestsSearch: "Номер, зал, вендор",
  colRequest: "Заявка",
  colEvent: "Событие",
  colDue: "Срок ответа",
  guests: (n: number) => `${n} гостей`,
  dueIn: "до",
  requestClient: "Клиент",
  requestComment: "Комментарий",
  requestBudget: "Бюджет",
  contactPurged: "Контакты клиента удалены по сроку хранения.",
  clientPhone: "Телефон клиента",
  clientPhoneHint: "Только администратор и только с причиной. Просмотр пишется в журнал.",
  clientPhoneReason: "Зачем нужен номер",
  vendorPhones: "Кому звонить у вендора",
  listingPhone: "Телефон карточки",
  firstResponse: "Первый ответ",
  firstViewed: "Просмотрена вендором",
  source: "Источник",
  reminders: (n: number) => `напоминаний: ${n}`,

  // работа с заявкой
  requestActions: "Работа с заявкой",
  remindVendor: "Напомнить вендору",
  remindHint: "Сообщение в Telegram всем, кто вошёл в кабинет вендора. Не чаще раза в 30 минут.",
  remindUnreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните.",
  remindAgainAt: (at: string) => `Следующее напоминание — после ${at}`,
  remindSent: "Напоминание отправлено",
  markContacted: "Связались",
  markContactedHint:
    "Отметка оператора: связь с клиентом состоялась. В ответы вендора она не засчитывается; клиенту уйдёт то же сообщение, что при ответе зала.",
  notAwaiting: "Заявка уже не ждёт первого ответа вендора.",
  timeline: "Срок ответа по шагам",
  timelineEvents: {
    created: "Заявка создана",
    viewed: "Вендор открыл заявку",
    due: "Срок ответа",
    dueFuture: "Срок ответа истекает",
    breached: "Срок нарушен: клиенту предложены похожие, команде — оповещение",
    response: "Первый ответ",
  },
  reminderAuto: (stage: number | null) => `Напоминание вендору (авто${stage ? `, этап ${stage}` : ""})`,
  reminderOps: (by: string | null) => `Напоминание от команды${by ? ` · ${by}` : ""}`,
  reminderDelivery: (recipients: number, delivered: number, failed: number) =>
    `получателей: ${recipients}, доставлено: ${delivered}${failed ? `, не доставлено: ${failed}` : ""}`,
  notes: "Заметки команды",
  notesHint: "Видны только сотрудникам. Добавить можно, изменить и удалить — нет. Без телефонов клиента.",
  notesEmpty: "Заметок нет.",
  noteText: "Новая заметка",
  addNote: "Добавить заметку",

  // клиенты
  clientsSearch: "Номер заявки или код клиента (C-…)",
  clientsSearchHint: "По имени и телефону не ищем.",
  clientsEmpty: "Клиентов не нашлось.",
  onlyBlocked: "Только заблокированные",
  colClient: "Клиент",
  colSince: "С нами с",
  colLastSeen: "Был в приложении",
  colRequests: "Заявки",
  colState: "Состояние",
  clientBlocked: "Заблокирован",
  clientDeleted: "Удалил аккаунт",
  clientActive: "Активен",
  clientProfile: "Профиль",
  clientName: "Имя в Telegram",
  clientUsername: "Имя пользователя",
  clientLocale: "Язык",
  clientCanMessage: "Бот может писать",
  clientDeletedNote: "Клиент удалил аккаунт: имени и телефона больше нет, заявки и журналы остались.",
  yes: "да",
  no: "нет",
  locales: { ru: "русский", uz: "узбекский" } as Record<string, string>,
  clientRequests: "Заявки клиента",
  clientConsents: "Журнал согласий",
  consentsEmpty: "Согласий нет.",
  consentPurposes: {
    client_service: "Аккаунт клиента",
    request_transfer: "Передача контактов вендору",
    bot_notifications: "Уведомления в боте",
    vendor_contact: "Данные контактного лица",
    vendor_phone_public: "Публикация телефона",
    vendor_offer: "Оферта",
  } as Record<string, string>,
  consentActions: { grant: "дал", withdraw: "отозвал" } as Record<string, string>,
  consentVersion: (v: number) => `версия текста ${v}`,
  blockTitle: "Блокировка",
  blockHint:
    "Заблокированный клиент не входит в приложение и не создаёт заявок. Причина обязательна; блокировка — в журнале.",
  block: "Заблокировать",
  unblock: "Снять блокировку",
  blockedSince: (at: string, by: string | null) => `Заблокирован ${at}${by ? ` · ${by}` : ""}`,
  clientPhoneProfile: "Телефон из профиля",

  // уведомления
  outboxCounts: {
    pending: "Ждут отправки",
    sending: "Отправляются",
    failed: "Повтор после сбоя",
    dead: "Не доставлены",
    sent: "Отправлено за сутки",
  } as Record<string, string>,
  outboxOldest: (at: string) => `Самое давнее ожидающее — с ${at}. Если давно, отправитель не работает.`,
  outboxDead: "Не доставлены",
  outboxDeadHint:
    "Бот не смог отправить сообщение: получатель заблокировал бота, не привязан или Telegram не ответил. Повтор ставит сообщение в очередь заново.",
  outboxDeadEmpty: "Всё доставлено.",
  outboxShown: (shown: number, total: number) => `Показаны последние ${shown} из ${total}.`,
  colKind: "Вид",
  colRecipient: "Получатель",
  colAttempts: "Попыток",
  colError: "Причина",
  colWhen: "Когда",
  recipientKinds: {
    client: "клиент",
    vendor_user: "вендор",
    staff: "сотрудник",
    system: "система",
  } as Record<string, string>,
  noticeKinds: {
    "vendor.request_new": "Вендору: новая заявка",
    "vendor.sla_reminder": "Вендору: напоминание (авто)",
    "vendor.ops_reminder": "Вендору: напоминание от команды",
    "client.request_status": "Клиенту: статус заявки",
    "client.sla_breach": "Клиенту: вендор молчит — похожие",
    "ops.sla_breach": "Команде: просрочка",
    "ops.outbox_dead": "Команде: не доставлено",
  } as Record<string, string>,

  // журнал
  auditTabs: { actions: "Действия", pii: "Просмотры телефонов" },
  auditActor: "Сотрудник",
  auditActorAny: "Любой",
  auditActorKind: "Кто",
  auditType: "Объект",
  auditTypeAny: "Любой",
  auditObject: "id объекта",
  auditAction: "Действие (начало кода)",
  auditFrom: "С",
  auditTo: "По",
  auditApply: "Показать",
  auditReset: "Сбросить",
  auditEmpty: "Записей нет.",
  auditPrev: "Новее",
  auditNext: "Старше",
  colActor: "Кто",
  colAction: "Действие",
  colObject: "Объект",
  colDetail: "Подробности",
  colPurpose: "Зачем",
  auditTypes: {
    vendor: "Вендор",
    vendor_user: "Пользователь кабинета",
    listing: "Карточка",
    request: "Заявка",
    client: "Клиент",
    staff: "Сотрудник",
    setting: "Настройка",
    outbox: "Уведомление",
    maintenance: "Обслуживание",
  } as Record<string, string>,
  piiSubjects: {
    client: "Клиент (профиль)",
    request_contact: "Клиент (заявка)",
    vendor_contact: "Контакт вендора",
    vendor_user: "Пользователь кабинета",
    listing_contact: "Телефон карточки",
  } as Record<string, string>,
  auditActions: {
    "listing.create": "Карточка создана",
    "listing.update": "Карточка изменена",
    "listing_package.create": "Пакет добавлен",
    "listing_package.update": "Пакет изменён",
    "listing_package.delete": "Пакет удалён",
    "listing_contact.create": "Телефон карточки вписан",
    "listing_contact.update": "Телефон карточки изменён",
    "listing_contact.delete": "Телефон карточки убран",
    "listing_revision.update": "Решение по правке",
    "photo.create": "Фото загружено",
    "photo.update": "Фото изменено",
    "availability.create": "День отмечен занятым",
    "availability.delete": "День освобождён",
    "vendor.create": "Вендор создан",
    "vendor.update": "Вендор изменён",
    "vendor_contact.create": "Контакты вендора вписаны",
    "vendor_contact.update": "Контакты вендора изменены",
    "vendor_user.create": "Пользователь кабинета заведён",
    "vendor_user.update": "Пользователь кабинета изменён",
    "vendor_user.telegram_claim": "Вендор привязал Telegram",
    "request.update": "Заявка изменена сотрудником",
    "request.remind": "Напоминание вендору",
    "request_note.create": "Заметка к заявке",
    "client.block": "Клиент заблокирован",
    "client.unblock": "Блокировка снята",
    "client.delete_account": "Клиент удалил аккаунт",
    "outbox.retry": "Повтор уведомления",
    "settings.update": "Настройка изменена",
    "staff.invite": "Сотрудник приглашён",
    "staff.role": "Роль изменена",
    "staff.deactivate": "Сотрудник отключён",
    "staff.activate": "Сотрудник включён",
    "staff.telegram_claim": "Приглашение принято",
    "maintenance.daily": "Ежедневное обслуживание",
  } as Record<string, string>,
  piiPurposes: {
    staff_reveal: "показать сотруднику",
    staff_vendor_contact: "звонок вендору",
    staff_vendor_user: "пользователь кабинета",
    staff_listing: "телефон карточки",
    request_inbox: "вендор в кабинете",
    self: "сам себе",
    system_notification: "уведомление",
  } as Record<string, string>,

  // команда
  inviteTitle: "Пригласить сотрудника",
  inviteHint:
    "Сотрудник войдёт через Telegram: имя пользователя должно совпадать с его именем в Telegram. При первом входе приглашение привяжется к его аккаунту.",
  inviteName: "Имя для панели",
  inviteUsername: "Имя пользователя Telegram",
  inviteRole: "Роль",
  invite: "Пригласить",
  invited: "Приглашение создано",
  colName: "Сотрудник",
  colRole: "Роль",
  colStatus: "Статус",
  you: "это вы",
  memberActive: "Действует",
  memberInactive: "Отключён",
  memberPending: "Ещё не входил",
  memberLinked: (at: string) => `Вошёл через Telegram ${at}`,
  changeRole: "Сменить роль",
  deactivate: "Отключить",
  activate: "Включить",
  deactivateHint: "Сотрудник сразу потеряет доступ: его сессии будут отозваны.",
  roleHints: {
    admin: "Всё, включая команду, настройки, журнал и телефоны клиентов",
    manager: "Вендоры и карточки, заявки и клиенты; не публикует",
    moderator: "Проверка и публикация карточек, фото и правок",
  } as Record<string, string>,

  // настройки
  settingsLabels: {
    sla_hours: "Срок ответа вендора, часов",
    sla_reminder_hours: "Напоминания вендору через, часов",
    quiet_hours: "Тихие часы (по Ташкенту)",
    min_photos: "Минимум фото для публикации",
    max_photos: "Максимум фото в карточке",
    client_requests_per_day: "Заявок клиента за сутки",
    request_contact_retention_days: "Хранить контакты из заявки, дней после события",
    session_retention_days: "Хранить истёкшие сессии, дней",
    otp_retention_hours: "Хранить коды входа, часов",
  } as Record<string, string>,
  settingsHints: {
    sla_hours:
      "1–72. Действует на новые заявки: у созданной срок уже зафиксирован. Напоминания — раньше срока.",
    sla_reminder_hours:
      "До двух, по возрастанию, каждое 1–72 и раньше срока ответа. Пусто — без напоминаний.",
    quiet_hours: "Ночью напоминания ждут утра. Начало и конец — ЧЧ:ММ.",
    min_photos: "3–10: меньше трёх нельзя — правило продукта. Не больше максимума.",
    max_photos: "3–30, не меньше минимума.",
    client_requests_per_day: "1–100: защита вендоров от спама.",
    request_contact_retention_days: "1–3650. Потом имя, телефон и комментарий стираются.",
    session_retention_days: "1–365.",
    otp_retention_hours: "1–720.",
  } as Record<string, string>,
  settingInvalid: "Значение не подходит: проверьте границы и согласованность с другими настройками.",
  settingValue: "Значение",
  reminderFirst: "Первое",
  reminderSecond: "Второе",
  quietFrom: "С",
  quietTo: "До",
  updatedBy: (at: string, by: string | null) => `Изменено ${at}${by ? ` · ${by}` : ""}`,
} as const;

/** Текст ошибки API по коду */
export function apiErrorText(code: string): string {
  return t.api[code] ?? t.api.unknown ?? "";
}
