/* Тексты панели оператора. Панель только на русском: ею пользуется команда, не клиенты.
   Узбекские здесь — только подписи полей, куда вписывают текст для клиентов на узбекском. */
export const t = {
  area: "панель оператора",
  skip: "К содержимому",
  sections: "Разделы панели",
  vendors: "Вендоры",
  vendorsLead: "Вендоры и их витрины: заведение, проверка, вход в кабинет.",
  moderation: "Модерация",
  moderationLead:
    "Всё, что ждёт решения: витрины, предложения изменений, услуги и новые фото. Клиенты видят прежнее, пока здесь не решат.",
  requests: "Заявки",
  requestsLead: "Заявки клиентов и ответы вендоров. Без ответа — вверху, ближайший срок первым.",
  clients: "Клиенты",
  clientsLead:
    "Имя из Telegram, чем входит и последняя заявка. Поиск — по номеру заявки или коду клиента (C-…). Выгрузки базы клиентов нет.",
  notifications: "Уведомления",
  notificationsLead: "Очередь сообщений бота: сколько ждёт отправки и что не доставлено.",
  audit: "Журнал",
  auditLead: "Кто, что и когда сделал в панели, и кто смотрел телефоны. Только чтение.",
  team: "Команда",
  teamLead: "Сотрудники панели: приглашение по имени в Telegram или по номеру телефона, роли, отключение.",
  settings: "Настройки",
  settingsLead: "Срок ответа, напоминания, фото, лимиты и сроки хранения. Каждое изменение — в журнале.",
  metrics: "Метрики",
  metricsLead:
    "Главное на запуске: клиент отправил заявку — вендор ответил в срок. Только числа: по неделям, категориям и вендорам.",
  noAccess: "У вашей роли нет доступа к этому разделу.",
  notFound: "Страница не найдена",
  notFoundLead: "Проверьте адрес или откройте главный раздел.",
  toSection: (section: string) => `Открыть «${section}»`,

  // несохранённые правки: уход со страницы
  unsavedTitle: "Уйти без сохранения?",
  unsavedText: "Изменения на этой странице не сохранены. Если уйти, они пропадут.",
  unsavedLeave: "Уйти",
  unsavedStay: "Остаться",

  // вход
  login: "Вход для сотрудников",
  loginLead:
    "Вход — аккаунтом Bayramm на сайте: через Telegram или по телефону. Доступ открывает администратор — по приглашению на ваше имя пользователя в Telegram или номер телефона.",
  // то же, когда входа по телефону в этом окружении нет (GET /auth/methods → phone: false)
  loginLeadTelegram:
    "Вход — аккаунтом Bayramm на сайте через Telegram. Доступ открывает администратор — по приглашению на ваше имя пользователя в Telegram.",
  loginChecking: "Проверяем вход…",
  loginHub: "Войти через Bayramm",
  loginStarting: "Переходим ко входу…",
  loginMiniApp: "В Telegram панель открывается кнопкой «Панель оператора» в боте.",
  loginOpenBot: "Открыть бота",
  toClientApp: "Приложение Bayramm",
  toCabinet: "Кабинет партнёра",
  retry: "Повторить",
  signOut: "Выйти",
  signedInAs: "Вы вошли как",
  errors: {
    invalid: "Вход не завершился или ссылка входа устарела. Войдите ещё раз.",
    denied:
      "Нет доступа к панели. Если вас пригласили, проверьте имя пользователя в Telegram или обратитесь к администратору.",
    reauth: "Вход был больше 12 часов назад. Войдите ещё раз — панель открывается только по свежему входу.",
    unavailable: "Сервер не отвечает. Попробуйте ещё раз через минуту.",
    expired:
      "Сессия закончилась: вход в панель действует 12 часов. Войдите ещё раз — откроется тот же экран.",
  },
  roles: {
    admin: "Администратор",
    manager: "Менеджер",
    moderator: "Модератор",
  },

  // заголовки экранов внутри разделов
  views: {
    vendorNew: "Новый вендор",
    vendor: "Вендор",
    listingNew: "Новая витрина",
    listing: "Витрина",
    request: "Заявка",
    client: "Клиент",
    revision: "Предложение изменений",
  },

  // общее
  loading: "Загружаем…",
  save: "Сохранить",
  saving: "Сохраняем…",
  saved: "Сохранено",
  cancel: "Отмена",
  back: "Назад",
  search: "Поиск",
  // кнопки своих контролов (@bayramm/ui/react): крестик шторки и очистка поля поиска
  close: "Закрыть",
  clear: "Очистить",
  // связь
  offline: "Нет подключения к интернету. Когда связь вернётся, данные загрузятся сами.",
  backOnline: "Связь вернулась.",
  all: "Все",
  none: "—",
  show: "Показать",
  hidden: "скрыт",
  notSet: "не указан",
  more: "Ещё",
  optional: "по желанию",

  // телефон и планшет: шапка, нижняя панель, шторки
  account: "Аккаунт",
  accountOf: (name: string, role: string) => `Аккаунт: ${name}, ${role}`,
  moreSections: "Ещё разделы",
  moreCurrent: (section: string) => `Ещё, открыт раздел «${section}»`,
  // Сотрудник решает по модерации, а бот ему не пишет: оповещения команды не доходят
  botBanner: "Уведомления от бота не приходят: напишите боту /start",
  botBannerLink: "Открыть бота",
  botBannerHide: "Скрыть",
  // Счётчики у разделов (из очередей метрик): что ждёт команду
  badges: {
    requests: (n: number) => `просрочено: ${n}`,
    moderation: (n: number) => `ждут решения: ${n}`,
    notifications: (n: number) => `не доставлено: ${n}`,
  },
  filters: "Фильтры",
  sort: "Сортировка",
  done: "Готово",
  reset: "Сбросить",
  actionsTitle: "Действия",
  listingActionsContext: "действия с витриной",
  total: (n: number) => `Всего: ${n}`,
  // Коды ошибок API → понятный текст. Неизвестный код — общий текст
  api: {
    network: "Нет связи с сервером. Проверьте соединение и попробуйте ещё раз.",
    unknown: "Что-то пошло не так. Попробуйте ещё раз.",
    internal_error: "Ошибка на сервере. Попробуйте ещё раз через минуту.",
    service_unavailable: "Сервер временно недоступен. Попробуйте через минуту.",
    forbidden: "Для этого действия у вашей роли нет прав.",
    not_found: "Не найдено: возможно, запись удалили или адрес неверный.",
    invalid_input: "Проверьте выделенные поля.",
    invalid_request: "Запрос не принят. Обновите страницу и попробуйте ещё раз.",
    payload_too_large: "Слишком большой файл или текст.",
    version_conflict: "Витрину только что изменили. Обновите страницу — ваши изменения не сохранены.",
    illegal_transition: "Из текущего статуса так нельзя. Обновите страницу.",
    publish_blocked: "Не хватает данных для этого шага:",
    reason_required: "Нужна причина.",
    slug_taken: "Этот адрес страницы уже у другой витрины — выберите другой.",
    stir_taken: "Этот СТИР уже у другого вендора.",
    phone_taken: "Этот номер уже заведён для входа у этого вендора.",
    user_linked: "Пользователь уже привязал Telegram — номер не сменить. Отключите его и заведите нового.",
    vendor_last_owner:
      "У кабинета должен остаться действующий владелец. Сначала назначьте владельцем другого пользователя или пригласите владельца.",
    vendor_user_exists: "Этот человек уже есть в кабинете вендора — под другим номером.",
    stir_missing: "Сначала впишите СТИР в реквизиты.",
    consent_text_missing: "Нет действующего текста согласия на обработку ПДн. Обратитесь к администратору.",
    checklist_locked: "Отметку не снять, пока витрины вендора опубликованы — сначала приостановите их.",
    too_many_photos: "Больше фото не добавить — достигнут предел.",
    duplicate_photo: "Это фото уже загружено.",
    invalid_image: "Фото не принято.",
    no_faces_ack_required: "Подтвердите, что на фото нет лиц.",
    photo_consent_required: "Подтвердите, что люди на фото согласны на публикацию.",
    photo_ack_required: "Отметка на фото не подходит категории: для неё фото должны быть без лиц.",
    category_locked:
      "Категорию не сменить: у витрины уже есть заявки или услуги. Заведите вендору новую витрину в нужной категории.",
    service_not_allowed: "Эта услуга недоступна для витрины.",
    service_invalid: "Предложение не проходит проверку полей услуги — его можно только отклонить.",
    too_many_services: "У витрины уже предельное число услуг.",
    no_changes: "Изменений нет — сохранять нечего.",
    storage_unavailable: "Хранилище фото недоступно. Попробуйте позже.",
    forbidden_for_actor: "Это действие недоступно.",
    moderated_field_requires_revision: "Поле меняется только через модерацию.",
    reminder_too_soon:
      "Вендору недавно уже напоминали — пауза между напоминаниями ещё не прошла. Попробуйте позже или позвоните.",
    request_not_awaiting: "Заявка уже не ждёт ответа вендора.",
    vendor_unreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните вендору.",
    staff_self: "Себя нельзя отключить или сменить себе роль.",
    staff_last_admin: "Должен остаться хотя бы один действующий администратор.",
    username_taken: "Это имя в Telegram уже у действующего сотрудника.",
    staff_phone_taken:
      "Этот номер уже у сотрудника команды. Если сотрудник отключён — включите его в списке ниже.",
    revision_invalid: "Предложение не проходит проверку полей — его можно только отклонить.",
    revision_pending:
      "У витрины уже есть предложение изменений, которое ждёт решения модератора. Пока по нему не решат, название и описания не изменить — ничего не сохранено.",
    calendar_conflict: "Календарь изменили — показали актуальный. Отметьте день ещё раз.",
    date_out_of_range: "Прошедший день не отметить и не снять. Если страница открыта давно — обновите её.",
    version_required: "Календарь устарел. Обновите страницу и отметьте день ещё раз.",
    client_blocked: "Клиент заблокирован.",
    // Общие ответы API, которые панель тоже может получить
    unauthorized: "Сессия закончилась. Войдите ещё раз.",
    reauth_required: "Вход был больше 12 часов назад. Войдите ещё раз.",
    account_disabled: "Аккаунт отключён. Обратитесь к администратору.",
    rate_limited: "Слишком много запросов подряд. Подождите минуту и попробуйте ещё раз.",
    conflict: "Такая запись уже есть. Обновите страницу и проверьте.",
    rule_violation: "Действие не прошло проверку правил. Обновите страницу и попробуйте ещё раз.",
    append_only: "Эту запись нельзя изменить или удалить — только добавить новую.",
    immutable_column: "Это поле после создания не меняется.",
    listing_not_active: "Витрина не опубликована — это действие недоступно.",
    consent_text_not_current: "Текст согласия обновился. Обновите страницу.",
    listing_in_use:
      "Витрину нельзя удалить: по ней есть заявки или она на проверке или в каталоге. Обновите страницу.",
    vendor_in_use:
      "Вендора нельзя удалить: у его витрин есть заявки или витрины на проверке или в каталоге. Обновите страницу.",
    staff_invite_accepted: "Приглашение уже принято — удалить его нельзя. Отключите сотрудника.",
  } as Record<string, string>,

  // статусы витрины
  status: {
    lead: "Лид",
    draft: "Черновик",
    review: "На проверке",
    active: "Опубликована",
    suspended: "Приостановлена",
    rejected: "Отклонена",
  },
  // Чего не хватает для проверки или публикации — коды app.listing_publish_blockers
  blockers: {
    price: "Услуга с ценой",
    capacity: "Вместимость (максимум гостей)",
    district: "Район",
    descriptions: "Описание на русском и узбекском",
    phone: "Телефон для клиентов",
    packages: "Обязательные услуги категории",
    attributes: "Обязательные данные витрины",
    photos: "Фото — не меньше минимума (для публикации — одобренные)",
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pd_consent: "Согласие на обработку ПДн подписано",
  } as Record<string, string>,
  blockersReview: "Не хватает для проверки",
  // переход от пункта «чего не хватает» к блоку, где он заполняется
  goTo: "Перейти",
  toChecklist: "К проверке вендора",
  blockersActive: "Не хватает для публикации",
  readyToPublish: "Всё готово к публикации",
  legalForms: { ooo: "ООО", yatt: "ЯТТ (ИП)", self_employed: "Самозанятый" },
  sum: "сум",

  // список вендоров
  newVendor: "Новый вендор",
  vendorsSearch: "Название, код, СТИР, телефон, контакт",
  vendorsEmpty: "Вендоров не нашлось.",
  vendorsEmptyAll: "Вендоров пока нет. Начните с «Новый вендор».",
  colVendor: "Вендор",
  colContact: "Контакт",
  colListings: "Витрины",
  colChecklist: "Проверка",
  colCabinet: "Кабинет",
  cabinetUsers: (users: number, linked: number) =>
    users === 0 ? "нет входа" : `${linked} из ${users} в Telegram`,
  noListings: "нет витрин",

  // вендор
  vendorCode: "Код",
  vendorSections: {
    business: "Бизнес",
    businessHint: "Название для панели и реквизиты. Скан документов не храним — только отметку о проверке.",
    contact: "Контакт",
    contactHint:
      "Контактное лицо вендора. Телефоны видны только по кнопке «Показать» — просмотр пишется в журнал.",
  },
  fields: {
    name: "Название",
    legalForm: "Форма",
    legalName: "Юрназвание",
    stir: "СТИР (9 цифр)",
    legalAddress: "Юрадрес",
    contractNo: "Номер договора",
    managerId: "Менеджер",
    contactPerson: "Контактное лицо",
    contactRole: "Должность",
    phone: "Телефон",
    phoneAlt: "Второй телефон",
    telegramUsername: "Telegram (@имя)",
  } as Record<string, string>,
  fieldErrors: {
    name: "От 2 до 120 символов",
    stir: "Ровно 9 цифр",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    phoneAlt: "Номер Узбекистана: +998 и 9 цифр",
    telegramUsername: "5–32 символа: латиница, цифры, _",
  } as Record<string, string>,
  phoneKeep: "Оставьте пустым, чтобы не менять",
  phoneNew: "Новый номер",
  createVendor: "Создать вендора",
  vendorActionsContext: "действия с вендором",
  vendorDelete: "Удалить вендора",
  vendorDeleteTitle: "Удалить вендора?",
  vendorDeleteText: (code: string) =>
    `Вендор ${code} удалится насовсем вместе со всеми витринами (фото, услуги, занятость, контакты), пользователями кабинета, реквизитами и контактами. Отменить нельзя.`,
  vendorDeleteCode: (code: string) => `Чтобы подтвердить, впишите код вендора: ${code}`,
  // Почему вендора нельзя удалить — DeleteBlocker
  vendorDeleteBlocked: {
    requests:
      "Удалить нельзя: по витринам вендора были заявки, их история хранится. Снимите витрины с публикации — приостановите.",
    published:
      "Удалить нельзя, пока витрины вендора на проверке или в каталоге: сначала верните их в черновик или приостановите.",
  } as Record<string, string>,
  vendorReadOnly: "Только просмотр: данные вендора меняют менеджер и администратор.",
  noManager: "Не назначен",

  checklist: "Проверка вендора",
  checklistHint: "Все четыре отметки нужны для публикации. Каждая отметка — в журнале действий.",
  checklistItems: {
    contract: "Договор подписан",
    stir: "СТИР сверен с реестром",
    contacts: "Контакты подтверждены звонком",
    pdConsent: "Согласие на обработку ПДн подписано",
  },
  checkedBy: (by: string | null, at: string) => (by ? `${by}, ${at}` : at),
  phones: "Телефоны контакта",
  phoneMain: "Основной",
  phoneAlternative: "Второй",

  users: "Вход в кабинет",
  usersHint:
    "Пригласите партнёра по номеру телефона — он войдёт сам: в боте Bayramm поделится контактом с этого номера или на сайте введёт код. Номер уже подтверждён в аккаунте Bayramm — доступ откроется сразу.",
  usersEmpty: "Пока никого нет — пригласите владельца кабинета.",
  userPhone: "Телефон для входа",
  userName: "Имя",
  disable: "Отключить",
  disableUserHint: "Человек сразу потеряет вход в кабинет. Включить его можно в любой момент.",
  enable: "Включить",
  // пользователи кабинета: приглашение, статус и действия (pages/VendorUsers.tsx)
  vuInviteTitle: "Пригласить в кабинет",
  vuRole: "Роль",
  vuRoles: { owner: "Владелец", member: "Сотрудник площадки" },
  vuRoleHints: {
    owner: "Меняет витрину, фото и услуги; отвечает на заявки и ведёт календарь",
    member: "Отвечает на заявки и ведёт календарь; витрину и услуги не меняет",
  },
  vuRoleRequired: "Выберите роль",
  vuOwnerFirst: "Сначала пригласите владельца: сотрудник площадки работает в кабинете вместе с ним.",
  vuLocale: "Язык уведомлений",
  vuLocales: { ru: "Русский", uz: "Oʻzbekcha" },
  vuLocaleHint: "На этом языке бот пишет партнёру; на нём же — текст приглашения",
  vuInvite: "Пригласить",
  vuInvited: "Приглашение создано — отправьте партнёру текст приглашения.",
  vuInvitedAccepted: "Номер уже подтверждён в аккаунте Bayramm — доступ открыт сразу.",
  vuStatus: { pending: "Ждёт входа", accepted: "Вошёл", disabled: "Отключён" },
  vuNoName: "Имя не указано",
  vuNotifiable: "Telegram: уведомления приходят",
  vuNotNotifiable: "Telegram: уведомления не приходят",
  vuOpenBot: "пусть партнёр откроет бота Bayramm",
  vuLastLogin: (at: string) => `Последний вход: ${at}`,
  vuNeverLoggedIn: "В кабинет ещё не входил",
  vuLocaleLine: (lang: string) => `Язык: ${lang}`,
  vuEdit: "Изменить",
  vuCopy: "Скопировать приглашение",
  vuCopied: "Приглашение скопировано",
  vuCopyTitle: "Текст приглашения",
  vuCopyHint: "Скопировать не получилось: выделите текст и скопируйте его сами.",
  vuUnlink: "Отвязать вход",
  vuUnlinkHint:
    "Партнёр потеряет вход в кабинет и уведомления о заявках, пока снова не подтвердит номер — контактом в боте или кодом на телефон.",
  vuRemove: "Убрать из кабинета",
  vuRemoveHintPending: "Приглашение удалится: по этому номеру в кабинет будет не войти.",
  vuRemoveHint:
    "Человек сразу потеряет доступ к кабинету этого вендора. Его аккаунт Bayramm и доступ к другим кабинетам останутся.",
  vuActions: "Действия с пользователем",

  listings: "Витрины",
  listingsEmpty: "У вендора пока нет витрин.",

  // витрина
  listingSections: {
    main: "Основное",
    mainHint: "Название, район и адрес страницы витрины на сайте (латиница).",
    texts: "Описание и адрес",
    textsHint: "На двух языках: клиент видит свой.",
    phone: "Телефон и Telegram для клиентов",
    phoneHint: "Клиент видит их сразу, до заявки. Telegram — по желанию.",
  },
  listingFields: {
    name: "Название",
    slug: "Адрес страницы (латиница)",
    districtCode: "Район",
    addressRu: "Адрес (RU)",
    addressUz: "Manzil (UZ)",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    capMin: "Гостей от",
    capMax: "Гостей до",
    phone: "Телефон",
    status: "Статус",
  } as Record<string, string>,
  listingFieldErrors: {
    name: "От 2 до 80 символов",
    slug: "Латиница, цифры и дефис, 3–40 символов",
    capMax: "Не меньше, чем «гостей от»",
    phone: "Номер Узбекистана: +998 и 9 цифр",
    telegram: "Имя пользователя или канала: 5–32 знака, латиница, цифры и «_»",
  } as Record<string, string>,
  category: "Категория",
  listingReadOnly: "Только просмотр: поля витрины меняют менеджер и администратор.",
  phoneMissing: "Телефона нет",
  phoneChange: "Сменить номер",
  telegramLabel: "Telegram",
  telegramMissing: "Telegram не указан",
  telegramChange: "Telegram для клиентов",
  telegramHintNew: "@имя, имя или ссылка t.me/имя. Можно не указывать",
  telegramRemove: "Убрать Telegram",
  phoneRemove: "Убрать телефон",
  phoneRemoveHint:
    "Клиенты не увидят ни телефона, ни Telegram витрины: Telegram уберётся вместе с телефоном.",
  contactsShow: "Показать",
  history: "История статусов",
  historyEmpty: "Пока без изменений.",
  historyBy: {
    staff: "сотрудник",
    vendor_user: "пользователь кабинета",
    system: "система",
    client: "клиент",
    account: "аккаунт",
  } as Record<string, string>,
  statusReason: "Причина",
  // Опубликованную витрину менеджер меняет предложением на модерацию (как вендор из кабинета)
  moderatedNotice:
    "Витрина опубликована: название, описания и услуги меняются через модерацию — клиенты видят прежнее, пока модератор не решит. Остальные поля сохраняются сразу.",
  moderatedHint: "Через модерацию",
  sentForModeration: (fields: string, rest: boolean) =>
    `Отправлено на модерацию: ${fields}. На витрине появится после решения модератора.${rest ? " Остальное сохранено." : ""}`,
  pendingRevisionTitle: "Предложение изменений ждёт решения модератора",
  pendingRevisionOpen: "Открыть предложение",

  actions: {
    submit: "Отправить на проверку",
    publish: "Опубликовать",
    suspend: "Приостановить",
    reject: "Отклонить",
    draft: "Вернуть в черновик",
  },
  actionHints: {
    publish: "Готовые фото витрины, ещё ждущие решения, будут одобрены.",
    suspend: "Витрина пропадёт из каталога. Причину увидит партнёр в кабинете.",
    reject: "Причину увидит партнёр в кабинете.",
    draft: "Комментарий попадёт в историю статусов.",
    submit: "Комментарий попадёт в историю статусов.",
  },
  reason: "Причина",
  comment: "Комментарий",

  // удаление витрины
  listingDelete: "Удалить витрину",
  listingDeleteTitle: "Удалить витрину?",
  listingDeleteHint:
    "Витрина удалится насовсем — вместе с фото, услугами, занятостью, контактами и предложениями изменений. Отменить нельзя.",
  listingDeleteText: (name: string) =>
    `«${name}» удалится насовсем: фото, услуги, занятость, контакты и предложения изменений. Отменить нельзя.`,
  // Почему витрину нельзя удалить — DeleteBlocker
  listingDeleteBlocked: {
    requests:
      "Удалить нельзя: по витрине были заявки, их история хранится. Чтобы витрины не было в каталоге, приостановите её.",
    published:
      "Удалить нельзя, пока витрина на проверке или в каталоге: сначала верните её в черновик или приостановите.",
  } as Record<string, string>,

  // фото
  photos: "Фото",
  photosHint: (min: number, max: number) =>
    `Минимум ${min}, максимум ${max}. Первое — обложка. Фото сжимаются в браузере, метаданные (в том числе геопозиция) удаляются.`,
  noFacesWarning:
    "На фото не должно быть людей и лиц — только то, что предлагает витрина: зал, машины, цветы, торты, подарки, оформление. Фото с людьми не загружайте.",
  noFacesAck: "Подтверждаю: на выбранных фото нет лиц",
  // Портфолио (фото и видео, студия): люди на фото — только с их согласия
  portfolioWarning:
    "Портфолио: люди на фото допустимы, только если они согласны на публикацию. Нет согласия — загружайте только фото без лиц.",
  photoAckLabel: "Что на выбранных фото",
  photoAckConsent: "Люди на фото согласны на публикацию",
  photoAckNoFaces: "На фото нет лиц",
  addPhotos: "Выбрать фото",
  photosDrop: "JPEG, PNG, WebP или HEIC — можно перетащить сюда",
  photosEmpty: "Фото ещё нет.",
  uploading: (done: number, total: number) => `Загружаем ${done} из ${total}…`,
  cover: "Обложка",
  makeCover: "Сделать обложкой",
  moveEarlier: (n: number) => `Фото ${n}: раньше`,
  moveLater: (n: number) => `Фото ${n}: позже`,
  photoN: (n: number) => `Фото ${n}`,
  addPhotosPhone: "Снять или выбрать фото",
  photosPick: "Камера или галерея: JPEG, PNG, WebP, HEIC",
  deletePhoto: "Удалить",
  deletePhotoTitle: "Удалить фото?",
  deletePhotoHint: "Фото пропадёт с витрины. Вернуть его можно, только загрузив заново.",
  approve: "Одобрить",
  decline: "Отклонить",
  // Отказ по фото — с причиной: её видит партнёр в кабинете
  declinePhotoTitle: (n: number) => `Отклонить фото ${n}`,
  declinePhotoHint: (n: number) =>
    `Фото ${n} не появится у клиентов. Причину увидит партнёр в кабинете — напишите, что переснять или заменить.`,
  declinePhoto: "Отклонить фото",
  photoDeclineReason: (reason: string) => `Причина отказа: ${reason}`,
  moderationStates: { pending: "Ждёт решения", approved: "Одобрено", declined: "Отклонено" },
  imageErrors: {
    empty: "пустой файл",
    too_large: "слишком большой файл",
    unsupported_format: "не фото или формат не поддерживается (нужны JPEG, PNG, WebP)",
    corrupt: "файл повреждён",
    animated: "анимация не подходит",
    metadata_present: "в файле остались метаданные",
    dimensions_too_large: "слишком большое разрешение",
    dimensions_too_small: "слишком маленькое фото (короткая сторона от 320 px)",
    decode_failed: "браузер не смог открыть файл (HEIC? сохраните как JPEG)",
    encode_failed: "браузер не смог подготовить фото",
  } as Record<string, string>,
  photoFailed: (name: string, why: string) => `${name}: ${why}`,

  // занятость
  availability: "Занятость",
  availabilityReadOnly: "Занятость витрины. Отмечают вендор, менеджер и администратор.",
  prevMonth: "Предыдущий месяц",
  nextMonth: "Следующий месяц",
  busy: "занят",
  rangeMode: "Несколько дней",
  rangePickStart: "Нажмите на первый день.",
  rangePickEnd: "Теперь — на последний день.",
  rangeChosen: (n: number) => `Выбрано дней: ${n}.`,
  rangeInside: "в выборе",
  rangeBusy: (n: number) => `Занять (${n})`,
  rangeFree: "Освободить",
  legend: "Обозначения",
  legendFree: "свободно",
  legendBusy: "занято",
  legendToday: "сегодня",
  legendChosen: "в выборе",
  busySources: {
    vendor: "отметил вендор",
    staff: "отметил сотрудник",
    request_decline: "отказ по заявке",
  } as Record<string, string>,
  weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],

  // модерация
  moderationEmpty: "Витрин на проверке нет.",
  submittedAt: "Отправлена",
  photosCount: (ready: number, approved: number) => `фото: ${ready}, одобрено: ${approved}`,
  listingsInReview: "Витрины на проверке",
  revisions: "Предложения изменений",
  revisionsHint:
    "Название, описания, данные и видео опубликованных витрин — от партнёра из кабинета или от менеджера.",
  revisionsEmpty: "Предложений, ждущих решения, нет.",
  revisionFields: {
    name: "Название",
    descriptionRu: "Описание (RU)",
    descriptionUz: "Tavsif (UZ)",
    attributes: "Данные витрины",
    videoLinks: "Видео",
  } as Record<string, string>,
  revisionStatus: {
    pending: "На проверке",
    approved: "Одобрено",
    declined: "Отклонено",
    withdrawn: "Отозвано партнёром",
  } as Record<string, string>,
  revisionStale:
    "Витрину меняли после того, как предложили изменения. Сравните «сейчас» и «предлагает» внимательно.",
  revisionInvalid: "Предложение не проходит проверку полей категории. Его можно только отклонить.",
  revisionField: "Поле",
  revisionNow: "Сейчас",
  revisionProposed: { partner: "Предлагает партнёр", staff: "Предлагает сотрудник" },
  // Кто предложил изменения: вендор из кабинета или сотрудник (менеджер) из панели
  proposedBy: (kind: "partner" | "staff", name: string | null) =>
    kind === "partner" ? "Предложил партнёр из кабинета" : `Предложил сотрудник${name ? ` · ${name}` : ""}`,
  revisionApprove: "Одобрить и применить",
  revisionApproveHint: "Новые значения сразу появятся на опубликованной витрине.",
  revisionDecline: "Отклонить",
  revisionDeclineHint: "Причину увидит партнёр в кабинете.",
  revisionWhoDecides: "Предложение ждёт решения: одобряет или отклоняет модератор или администратор.",
  revisionDecided: (status: string, by: string | null, at: string) =>
    `${status}${by ? ` · ${by}` : ""} · ${at}`,
  openListing: "К витрине",
  photoQueue: "Новые фото",
  photoQueueHint:
    "Новые фото — от партнёра или менеджера, и у черновиков тоже. Одобрить или отклонить — на странице витрины; что не решите, одобрит публикация.",
  photoQueueEmpty: "Новых фото, ждущих решения, нет.",
  pendingPhotos: (n: number) => `ждут решения: ${n}`,

  // заявки
  requestsEmpty: "Заявок нет.",
  requestNo: (n: number) => `№ ${n}`,
  requestsCount: (n: number) => `заявок: ${n}`,
  sla: {
    waiting: "Ждёт ответа",
    overdue: "Просрочена",
    breached: "Нарушен срок",
    answered: "Ответ в срок",
    answered_late: "Ответ с опозданием",
    ops_contacted: "Связались мы",
    closed: "Закрыта",
  } as Record<string, string>,
  slaLate: "Требуют действия",
  requestStatus: {
    new: "Новая",
    viewed: "Просмотрена",
    contacted: "Вендор связался",
    deal: "Договорились",
    declined: "Отказ вендора",
    withdrawn: "Отозвана клиентом",
    expired: "Истекла",
  } as Record<string, string>,
  declineReasons: {
    busy: "Занято",
    format: "Не наш формат",
    price: "Не сошлись в цене",
    other: "Другое",
  } as Record<string, string>,
  requestsSearch: "Номер, витрина, вендор",
  colRequest: "Заявка",
  colListing: "Витрина",
  createdAt: (at: string) => `создана ${at}`,
  colEvent: "Событие",
  colDue: "Срок ответа",
  guests: (n: number | null) => (n === null ? "гости не указаны" : `${n} гостей`),
  dueIn: "до",
  requestClient: "Клиент",
  requestComment: "Комментарий",
  requestBudget: "Бюджет",
  contactPurged: "Контакты клиента удалены по сроку хранения.",
  clientPhone: "Телефон клиента",
  clientPhoneHint: "Только администратор и только с причиной. Просмотр пишется в журнал.",
  clientPhoneReason: "Зачем нужен номер",
  vendorPhones: "Кому звонить у вендора",
  listingPhone: "Телефон для клиентов",
  firstResponse: "Первый ответ",
  firstViewed: "Просмотрена вендором",
  source: "Откуда заявка",
  // Откуда пришла запись (app.source): словами, а не кодом базы
  sources: {
    tma: "Mini App",
    web: "Сайт",
    vendor_cabinet: "Кабинет партнёра",
    partner_bot: "Бот партнёра",
    admin: "Панель оператора",
    offline: "Не из приложения",
    system: "Система",
  } as Record<string, string>,
  reminders: (n: number) => `напоминаний: ${n}`,

  // работа с заявкой
  requestActions: "Работа с заявкой",
  remindVendor: "Напомнить вендору",
  remindHint:
    "Сообщение в Telegram всем, кто вошёл в кабинет вендора. Между напоминаниями — пауза из настроек.",
  remindUnreachable: "У вендора никто не привязал Telegram — напоминание не дойдёт. Позвоните.",
  remindAgainAt: (at: string) => `Следующее напоминание — после ${at}`,
  remindSent: "Напоминание отправлено",
  markContacted: "Связались",
  markContactedHint:
    "Отметка оператора: связь с клиентом состоялась. В ответы вендора она не засчитывается; клиенту уйдёт то же сообщение, что при ответе вендора.",
  notAwaiting: "Заявка уже не ждёт первого ответа вендора.",
  timeline: "Срок ответа по шагам",
  timelineEvents: {
    created: "Заявка создана",
    viewed: "Вендор открыл заявку",
    due: "Срок ответа",
    dueFuture: "Срок ответа истекает",
    breached: "Срок нарушен: клиенту предложены похожие, команде — оповещение",
    response: "Первый ответ",
  },
  reminderAuto: (stage: number | null) => `Напоминание вендору (авто${stage ? `, этап ${stage}` : ""})`,
  reminderOps: (by: string | null) => `Напоминание от команды${by ? ` · ${by}` : ""}`,
  reminderDelivery: (recipients: number, delivered: number, failed: number) =>
    `получателей: ${recipients}, доставлено: ${delivered}${failed ? `, не доставлено: ${failed}` : ""}`,
  notes: "Заметки команды",
  notesHint: "Видны только сотрудникам. Добавить можно, изменить и удалить — нет. Без телефонов клиента.",
  notesEmpty: "Заметок нет.",
  noteText: "Новая заметка",
  addNote: "Добавить заметку",

  // клиенты
  clientsSearch: "Номер заявки или код клиента (C-…)",
  clientsSearchHint: "По имени и телефону не ищем.",
  clientsEmpty: "Клиентов не нашлось.",
  onlyBlocked: "Только заблокированные",
  colClient: "Клиент",
  clientNoName: "Без имени",
  clientAccountDeleted: "Аккаунт удалён",
  clientNoNameTitle: "Клиент без имени",
  clientDeletedTitle: "Клиент удалил аккаунт",
  colSignIn: "Вход и язык",
  clientSignIn: "Вход",
  signInKinds: { telegram: "Telegram", phone: "телефон" } as Record<string, string>,
  signInNone: "нет способа входа",
  clientNoRequests: "заявок нет",
  colSince: "С нами с",
  colLastSeen: "Был в приложении",
  colRequests: "Заявки",
  colState: "Состояние",
  clientBlocked: "Заблокирован",
  clientDeleted: "Удалил аккаунт",
  clientActive: "Активен",
  clientProfile: "Профиль",
  clientName: "Имя в Telegram",
  clientUsername: "Имя пользователя",
  clientLocale: "Язык",
  clientCanMessage: "Бот может писать",
  clientDeletedNote: "Клиент удалил аккаунт: имени и телефона больше нет, заявки и журналы остались.",
  yes: "да",
  no: "нет",
  locales: { ru: "русский", uz: "узбекский" } as Record<string, string>,
  clientRequests: "Заявки клиента",
  clientConsents: "Журнал согласий",
  consentsEmpty: "Согласий нет.",
  consentPurposes: {
    client_service: "Аккаунт клиента",
    request_transfer: "Передача контактов вендору",
    bot_notifications: "Уведомления в боте",
    vendor_contact: "Данные контактного лица",
    vendor_phone_public: "Публикация телефона",
    vendor_offer: "Оферта",
  } as Record<string, string>,
  consentActions: { grant: "дал", withdraw: "отозвал" } as Record<string, string>,
  consentVersion: (v: number) => `версия текста ${v}`,
  blockTitle: "Блокировка",
  blockHint:
    "Заблокированный клиент не входит в приложение и не создаёт заявок. Причина обязательна; блокировка — в журнале.",
  block: "Заблокировать",
  unblock: "Снять блокировку",
  unblockHint: "Клиент снова сможет входить в приложение и отправлять заявки. Снятие — в журнале.",
  blockedSince: (at: string, by: string | null) => `Заблокирован ${at}${by ? ` · ${by}` : ""}`,
  clientPhoneProfile: "Телефон из профиля",

  // уведомления
  outboxCounts: {
    pending: "Ждут отправки",
    sending: "Отправляются",
    failed: "Повтор после сбоя",
    dead: "Не доставлены",
    sent: "Отправлено за сутки",
  } as Record<string, string>,
  outboxOldest: (at: string) => `Самое давнее ожидающее — с ${at}. Если давно, отправитель не работает.`,
  outboxDead: "Не доставлены",
  outboxDeadHint:
    "Бот не смог отправить сообщение: получатель заблокировал бота, не привязан или Telegram не ответил. Повтор ставит сообщение в очередь заново.",
  outboxDeadEmpty: "Всё доставлено.",
  retryNotice: (kind: string) => `Повторить: ${kind}`,
  outboxShown: (shown: number, total: number) => `Показаны последние ${shown} из ${total}.`,
  colKind: "Вид",
  colRecipient: "Получатель",
  colAttempts: "Попыток",
  colError: "Причина",
  colWhen: "Когда",
  recipientKinds: {
    client: "клиент",
    vendor_user: "пользователь кабинета",
    staff: "сотрудник",
    system: "система",
  } as Record<string, string>,
  noticeKinds: {
    "vendor.request_new": "Вендору: новая заявка",
    "vendor.sla_reminder": "Вендору: напоминание (авто)",
    "vendor.ops_reminder": "Вендору: напоминание от команды",
    "client.request_status": "Клиенту: статус заявки",
    "client.sla_breach": "Клиенту: вендор молчит — похожие",
    "ops.sla_breach": "Команде: просрочка",
    "ops.outbox_dead": "Команде: не доставлено",
    "ops.revision_submitted": "Команде: предложение изменений витрины",
    "ops.daily_digest": "Команде: утренняя сводка",
    "ops.weekly_report": "Команде: отчёт за неделю",
    "ops.api_error": "Команде: ошибки сервера",
    "vendor.access_granted": "Вендору: добавлен в кабинет",
  } as Record<string, string>,

  // журнал
  auditTabs: { actions: "Действия", pii: "Просмотры телефонов" },
  auditActor: "Сотрудник",
  auditActorAny: "Любой",
  auditActorKind: "Кто",
  auditType: "Вид объекта",
  auditTypeAny: "Любой",
  auditObject: "Объект",
  auditAction: "Что сделали",
  auditActionAny: "Любое действие",
  // Группы действий: значение фильтра — начало кода действия на сервере (listing. → listing.update…)
  auditActionGroups: {
    "listing.": "Витрины",
    "listing_service.": "Услуги",
    "listing_contact.": "Контакты витрин",
    "listing_revision.": "Предложения изменений",
    "photo.": "Фото",
    "availability.": "Занятость",
    "vendor.": "Вендоры",
    "vendor_contact.": "Контакты вендоров",
    "vendor_user.": "Пользователи кабинета",
    "request.": "Заявки",
    "client.": "Клиенты",
    "staff.": "Команда",
    "settings.": "Настройки",
    "outbox.": "Уведомления",
    "maintenance.": "Обслуживание",
  } as Record<string, string>,
  // Ключи подробностей записи журнала словами; неизвестные показываются как записаны
  auditDetailKeys: {
    fields: "поля",
    from: "было",
    to: "стало",
    recipients: "получателей",
    role: "роль",
    kind: "вид",
    day: "день",
    reason: "причина",
    status: "статус",
    category: "категория",
    code: "код",
    via: "как пригласили",
    photos: "фото",
    services: "услуг",
    revisions: "предложений изменений",
    busy_days: "отметок занятости",
    listings: "витрин",
    users: "пользователей кабинета",
    accepted: "принято сразу",
    had_account: "входил",
  } as Record<string, string>,
  auditVia: { phone: "по телефону", telegram: "по имени в Telegram" } as Record<string, string>,
  // Имена полей витрины и вендора в подробностях («fields»): столбцы базы → слова
  auditFields: {
    name: "название",
    slug: "адрес страницы",
    status: "статус",
    status_reason: "причина статуса",
    category_code: "категория",
    district_code: "район",
    address_ru: "адрес (RU)",
    address_uz: "адрес (UZ)",
    description_ru: "описание (RU)",
    description_uz: "описание (UZ)",
    cap_min: "гостей от",
    cap_max: "гостей до",
    price_from_uzs: "цена от",
    price_unit: "единица цены",
    attributes: "данные витрины",
    video_links: "видео",
    parallel_capacity: "заказов одновременно",
    lead_days: "срок заказа",
    phone: "телефон",
    telegram: "Telegram",
    phone_alt: "второй телефон",
    legal_name: "юрназвание",
    legal_form: "форма",
    stir: "СТИР",
    legal_address: "юрадрес",
    contract_no: "номер договора",
    contact_person: "контактное лицо",
    contact_role: "должность",
    telegram_username: "Telegram",
  } as Record<string, string>,
  auditFrom: "С",
  auditTo: "По",
  auditAnyDate: "любая дата",
  auditNoDate: "Без даты",
  auditApply: "Показать",
  auditReset: "Сбросить",
  auditEmpty: "Записей нет.",
  auditPrev: "Новее",
  auditNext: "Старше",
  colActor: "Кто",
  colAction: "Действие",
  colObject: "Объект",
  colDetail: "Подробности",
  colPurpose: "Зачем",
  auditTypes: {
    vendor: "Вендор",
    vendor_user: "Пользователь кабинета",
    listing: "Витрина",
    request: "Заявка",
    client: "Клиент",
    staff: "Сотрудник",
    setting: "Настройка",
    outbox: "Уведомление",
    maintenance: "Обслуживание",
  } as Record<string, string>,
  piiSubjects: {
    client: "Клиент (профиль)",
    request_contact: "Клиент (заявка)",
    vendor_contact: "Контакт вендора",
    vendor_user: "Пользователь кабинета",
    listing_contact: "Контакты витрины",
  } as Record<string, string>,
  auditActions: {
    "listing.create": "Витрина создана",
    "listing.update": "Витрина изменена",
    "listing_package.create": "Пакет добавлен",
    "listing_package.update": "Пакет изменён",
    "listing_package.delete": "Пакет удалён",
    "listing_contact.create": "Контакты витрины вписаны",
    "listing_contact.update": "Контакты витрины изменены",
    "listing_contact.delete": "Контакты витрины убраны",
    "listing.category_change": "Категория витрины изменена",
    "listing.delete": "Витрина удалена",
    "listing_service.create": "Услуга добавлена",
    "listing_service.update": "Услуга изменена",
    "listing_service.delete": "Услуга удалена",
    "listing_revision.update": "Решение по предложению изменений",
    "photo.create": "Фото загружено",
    "photo.update": "Фото изменено",
    "availability.create": "День отмечен занятым",
    "availability.delete": "День освобождён",
    "vendor.create": "Вендор создан",
    "vendor.update": "Вендор изменён",
    "vendor_contact.create": "Контакты вендора вписаны",
    "vendor_contact.update": "Контакты вендора изменены",
    "vendor_user.create": "Пользователь кабинета заведён",
    "vendor_user.update": "Пользователь кабинета изменён",
    "vendor_user.telegram_claim": "Вендор привязал Telegram",
    "vendor_user.account_bind": "Вендор вошёл аккаунтом Bayramm",
    "vendor_user.invite": "Приглашение в кабинет",
    "vendor_user.remove": "Пользователь убран из кабинета",
    "vendor.listing_add": "Вендору добавлена витрина",
    "vendor.delete": "Вендор удалён",
    "request.update": "Заявка изменена сотрудником",
    "request.remind": "Напоминание вендору",
    "request_note.create": "Заметка к заявке",
    "client.block": "Клиент заблокирован",
    "client.unblock": "Блокировка снята",
    "client.delete_account": "Клиент удалил аккаунт",
    "outbox.retry": "Повтор уведомления",
    "settings.update": "Настройка изменена",
    "staff.invite": "Сотрудник приглашён",
    "staff.invite_revoke": "Приглашение отозвано",
    "staff.role": "Роль изменена",
    "staff.deactivate": "Сотрудник отключён",
    "staff.activate": "Сотрудник включён",
    "staff.telegram_claim": "Приглашение принято",
    "staff.phone_claim": "Приглашение принято по телефону",
    "staff.elevate": "Вход в панель",
    "outbox.no_recipients": "Оповещение команды некому отправить",
    "maintenance.daily": "Ежедневное обслуживание",
  } as Record<string, string>,
  piiPurposes: {
    staff_reveal: "показать сотруднику",
    staff_vendor_contact: "звонок вендору",
    staff_vendor_user: "пользователь кабинета",
    staff_listing: "телефон витрины",
    request_inbox: "вендор в кабинете",
    self: "сам себе",
    system_notification: "уведомление",
  } as Record<string, string>,

  // команда
  inviteTitle: "Пригласить сотрудника",
  inviteHint:
    "Сотрудник войдёт через Telegram: имя пользователя должно совпадать с его именем в Telegram. При первом входе приглашение привяжется к его аккаунту.",
  inviteHintPhone:
    "Сотрудник войдёт на сайте Bayramm по коду на этот номер — при первом входе приглашение привяжется к его аккаунту. Если номер уже подтверждён в аккаунте Bayramm, приглашение примется сразу. Номер не хранится: только его отпечаток.",
  inviteHintPhoneOff:
    "Вход по коду на телефон в этом окружении пока выключен: приглашение примется, когда сотрудник подтвердит номер в аккаунте Bayramm. Номер не хранится: только его отпечаток.",
  inviteBy: "Как войдёт",
  inviteByTelegram: "По имени в Telegram",
  inviteByPhone: "По номеру телефона",
  inviteName: "Имя для панели",
  inviteUsername: "Имя пользователя Telegram",
  invitePhone: "Номер телефона",
  inviteRole: "Роль",
  invite: "Пригласить",
  invited: "Приглашение создано",
  invitedByPhone: "по телефону",
  colName: "Сотрудник",
  colRole: "Роль",
  colStatus: "Статус",
  you: "это вы",
  memberActive: "Действует",
  memberInactive: "Отключён",
  memberPending: "Ещё не входил",
  memberAccepted: "Приглашение принято",
  memberLinked: (at: string) => `Вошёл через Telegram ${at}`,
  // чата с ботом нет — оповещения команды ему не приходят
  memberNoBot: "бот: нет",
  memberNoBotHint: "оповещения не приходят: не писал боту /start",
  changeRole: "Сменить роль",
  deactivate: "Отключить",
  activate: "Включить",
  deactivateHint: "Сотрудник сразу потеряет доступ: его сессии будут отозваны.",
  inviteRevoke: "Отозвать приглашение",
  inviteRevokeTitle: "Отозвать приглашение?",
  inviteRevokeText: (name: string) =>
    `Приглашение «${name}» удалится: войти по нему будет нельзя. Пригласить снова можно в любой момент.`,
  activateHint: "Сотрудник снова сможет входить в панель — с той же ролью.",
  roleHints: {
    admin: "Всё, включая команду, настройки, журнал и телефоны клиентов",
    manager: "Вендоры и витрины, заявки и клиенты; не публикует",
    moderator: "Проверка и публикация витрин, фото, услуг и предложений изменений",
  } as Record<string, string>,

  // настройки
  settingsLabels: {
    sla_hours: "Срок ответа вендора, часов",
    sla_reminder_hours: "Напоминания вендору через, часов",
    quiet_hours: "Тихие часы (по Ташкенту)",
    ops_reminder_pause_minutes: "Пауза между напоминаниями от команды, минут",
    min_photos: "Минимум фото для публикации",
    max_photos: "Максимум фото на витрине",
    client_requests_per_day: "Заявок клиента за сутки",
    request_contact_retention_days: "Хранить контакты из заявки, дней после события",
    session_retention_days: "Хранить истёкшие сессии, дней",
    otp_retention_hours: "Хранить коды входа, часов",
  } as Record<string, string>,
  settingsHints: {
    sla_hours:
      "1–72. Действует на новые заявки: у созданной срок уже зафиксирован. Напоминания — раньше срока.",
    sla_reminder_hours:
      "До двух, по возрастанию, каждое 1–72 и раньше срока ответа. Пусто — без напоминаний.",
    quiet_hours: "Ночью напоминания ждут утра. Начало и конец — ЧЧ:ММ.",
    ops_reminder_pause_minutes:
      "5–1440. Кнопка «Напомнить» на заявке снова доступна через столько минут после прошлого напоминания.",
    min_photos: "3–10: меньше трёх нельзя — правило продукта. Не больше максимума.",
    max_photos: "3–30, не меньше минимума.",
    client_requests_per_day: "1–100: защита вендоров от спама.",
    request_contact_retention_days: "1–3650. Потом имя, телефон и комментарий стираются.",
    session_retention_days: "1–365.",
    otp_retention_hours: "1–720.",
  } as Record<string, string>,
  settingInvalid: "Значение не подходит: проверьте границы и согласованность с другими настройками.",
  settingValue: "Значение",
  reminderFirst: "Первое",
  reminderSecond: "Второе",
  quietFrom: "С",
  quietTo: "До",
  updatedBy: (at: string, by: string | null) => `Изменено ${at}${by ? ` · ${by}` : ""}`,

  // метрики запуска
  metricsNow: "Сейчас",
  metricsQueues: {
    awaiting: "Ждут ответа вендора",
    overdue: "Из них срок вышел",
    deadTotal: "Не доставлено уведомлений",
    listingsReview: "Витрин на проверке",
    revisionsPending: "Предложений ждут решения",
    photosPending: "Новых фото ждут решения",
    servicesPending: "Услуг ждут решения",
  } as Record<string, string>,
  metricsWeekly: "По неделям",
  metricsWeeklyHint: (hours: number) =>
    `Неделя — с понедельника, по Ташкенту; заявка — в неделе, когда её отправили. «В срок» — вендор сам ответил за ${hours} ч: связались, договорились или отказ. Просмотр, звонок и «связались» от команды — не ответ вендора. Доля — от заявок, исход которых известен: вендор ответил в срок или срок уже прошёл; отозванные клиентом до срока без ответа — не в расчёте. Время ответа — по заявкам с ответом вендора.`,
  metricsCategories: "По категориям за 30 дней",
  metricsCategoriesHint:
    "Категория заявки — категория витрины. Опубликованные витрины и их вендоры — сейчас; заявки, ответы и договорённости — за 30 дней.",
  metricsCategoryFilter: (name: string) =>
    `Недели, вендоры и контакты — только «${name}». Очереди и сводка выше — по всем категориям.`,
  metricsFilterScope: "Категория — для недель, вендоров и контактов ниже.",
  metricsContacts: "Контакты витрин за 30 дней",
  metricsContactsHint:
    "Как часто клиенты открывали окно контактов витрины и нажимали «Позвонить» или «Написать в Telegram». Только числа, без клиентов. Сверху — чаще открывают; под числом открытий — на сколько их больше или меньше, чем в предыдущие 30 дней.",
  // Изменение числа открытий к предыдущему такому же периоду: знак — не только цветом
  opensChange: (now: number, prev: number) =>
    now === prev
      ? `без изменений · было ${prev}`
      : `${now > prev ? "+" : "−"}${Math.abs(now - prev)} · было ${prev}`,
  // Для диктора; период в запросе всегда 30 дней, поэтому «дней» без склонения
  opensChangeSpoken: (now: number, prev: number, days: number) =>
    now === prev
      ? `Столько же, сколько за предыдущие ${days} дней: ${prev}.`
      : `На ${Math.abs(now - prev)} ${now > prev ? "больше" : "меньше"}, чем за предыдущие ${days} дней: тогда было ${prev}.`,
  metricsContactsEmpty: "За 30 дней контакты витрин никто не открывал.",
  colContactOpens: "Открыли контакты",
  colContactPhone: "Позвонить",
  colContactTelegram: "Telegram",
  weekNumber: (n: number) => `неделя ${n}`,
  metricsVendors: "Вендоры за 30 дней",
  metricsVendorsHint:
    "Вендоры с заявками за 30 дней или с опубликованной витриной. По умолчанию худшие по доле ответов в срок — сверху: им стоит позвонить.",
  metricsVendorsEmpty: "Пока нет ни заявок, ни опубликованных витрин.",
  colWeek: "Неделя",
  colAnswered: "Ответ в срок",
  colResponseTime: "Время ответа",
  colMedian: "Медиана ответа",
  colAgreed: "Договорились",
  colBreaches: "Срок сорван",
  colDead: "Не доставлено",
  colLastRequest: "Последняя заявка",
  weekNow: "идёт",
  clientsCount: (n: number) => `клиентов: ${n}`,
  answeredOf: (answered: number, measurable: number) => `${answered} из ${measurable}`,
  medianTime: (median: string) => `медиана ${median}`,
  p90Time: (p90: string) => `у 90% — до ${p90}`,
  sortAsc: "по возрастанию",
  sortDesc: "по убыванию",
  // Сортировка вендоров на телефоне: столбец и направление одним выбором
  sortRateAsc: "Меньше ответов в срок — сверху",
  sortRateDesc: "Больше ответов в срок — сверху",
  sortRequestsDesc: "Больше заявок — сверху",
  sortMedianDesc: "Дольше отвечают — сверху",
  vendorResponse: "Ответы на заявки",
  vendorResponseHint:
    "За 30 дней. «В срок» — вендор сам ответил за срок заявки; «связались» от команды не считается.",
  vendorResponseEmpty: "За 30 дней заявок не было.",
  activeListings: (n: number) => `опубликовано витрин: ${n}`,
  activeVendors: (n: number) => `вендоров: ${n}`,
  vendorCategories: "Категории",

  // ── категории, витрины, услуги (v0.2) ──
  colCategory: "Категория",
  allCategories: "Все категории",
  categoryFirst: "Категория витрины",
  categoryFirstHint: "С ней заведётся первая витрина. Другие — потом, на странице вендора.",
  categoryRequired: "Выберите категорию",
  vitrinasHint:
    "Витрина — страница вендора в одной категории: свои данные, услуги, фото, занятость и заявки. Вход в кабинет, контакты и проверка — общие у вендора.",
  addVitrina: "Добавить витрину в другой категории",
  addVitrinaLead:
    "Новая витрина появится черновиком: дальше — данные витрины, услуги и фото на её странице. Категорию партнёр не меняет.",
  vitrinaHas: (names: string) => `Уже есть: ${names}`,
  vitrinaName: "Название витрины",
  vitrinaNameHint: "Пусто — название вендора",
  createVitrina: "Создать витрину",
  categoryChange: "Сменить категорию",
  categoryChangeHint:
    "Только пока у витрины нет заявок и услуг: данные витрины очистятся. Если категория другая по сути — лучше новая витрина.",
  categoryChangeLocked:
    "У витрины есть услуги — категорию не сменить. Заведите вендору новую витрину в нужной категории.",
  categoryNew: "Новая категория",
  required: "обязательно",
  priceFromAuto: "Цена «от» в каталоге — из одобренных услуг",
  priceFromNone: "появится с первой услугой с ценой",
  listingDataSections: {
    attributes: "Данные витрины",
    attributesHint: (category: string) =>
      `Поля категории «${category}»: по ним клиент фильтрует каталог. Обязательные нужны для публикации.`,
    occupancy: "Заказов одновременно",
    occupancyHint:
      "Сколько машин, экипажей или команд работают в одно время. Часть дня занята, когда договорённостей на неё столько же.",
    videos: "Видео",
    videosHint: (n: number) =>
      `До ${n} ссылок на ролики YouTube или посты Instagram. Файлы видео не загружаются.`,
  },
  attributeError: "Проверьте значение",
  attributeIntError: (min: number, max: number) => `Целое число от ${min} до ${max}`,
  listAdd: "Добавить",
  listRemove: "Убрать",
  listItem: (label: string, n: number) => `${label}, № ${n}`,
  listEmpty: "Пока пусто.",
  listLimit: (n: number) => `До ${n} записей`,
  videoLink: (n: number) => `Ссылка ${n}`,
  videoAdd: "Добавить ссылку",
  videoRemove: "Убрать ссылку",
  videoLinkError: "Нужна ссылка на ролик YouTube или пост Instagram",
  parallelCapacityError: "Целое число от 1 до 50",
  readinessAttributes: (labels: string) => `Не заполнено: ${labels}`,
  readinessServices: (labels: string) => `Нужны услуги: ${labels}`,
  readinessPhotos: (n: number, min: number) => `Фото: ${n} из ${min}`,

  // услуги витрины
  services: "Услуги",
  // Цена «от» объяснена один раз — строкой «Цена «от» в каталоге — из одобренных услуг: …» ниже
  servicesHint: "Цены витрины — только в услугах: «по запросу» не бывает.",
  servicesEmpty: "Услуг пока нет.",
  servicesDecides: "Вы решаете по модерации: ваши услуги и их изменения сразу на витрине.",
  servicesManager:
    "Новые услуги и изменения услуг опубликованной витрины уходят модератору; у неопубликованной их одобрит модератор или публикация.",
  // услуга ждёт решения прямо на странице витрины (как в очереди «Модерации»)
  serviceWaits: "Ждёт решения",
  serviceStatus: {
    draft: "Черновик",
    review: "На проверке",
    active: "На витрине",
    rejected: "Отклонена",
    paused: "Снята с витрины",
  } as Record<string, string>,
  serviceProposal: "Изменения на проверке",
  serviceDeclined: (reason: string) => `Отклонена: ${reason}`,
  serviceProposalDeclined: (reason: string) => `Изменения отклонены: ${reason}`,
  serviceMin: (n: number, unit: string) => `минимум ${n}, ${unit}`,
  serviceLead: (n: number) => `заказ за ${n} дн.`,
  serviceNew: "Новая услуга",
  serviceAdd: "Добавить услугу",
  serviceAddFrom: "Услуга из каталога категории",
  serviceEdit: "Изменить",
  serviceEditTitle: (name: string) => `Услуга: ${name}`,
  serviceSave: "Сохранить услугу",
  serviceCreate: "Добавить услугу",
  servicePause: "Снять с витрины",
  serviceResume: "Вернуть на витрину",
  serviceSubmit: "Отправить на проверку",
  serviceDelete: "Удалить услугу",
  serviceDeleteTitle: "Удалить услугу?",
  serviceDeleteHint: "Услуга пропадёт из витрины. Заявки, где её выбрали, сохранят её как была.",
  serviceFields: {
    type: "Услуга",
    nameRu: "Название (RU)",
    nameUz: "Nomi (UZ)",
    priceUzs: "Цена, сум",
    priceUnit: "За что",
    minQty: "Минимальный заказ",
    minQtyHint: "Например, от 3 часов или от 50 штук. Пусто — без минимума",
    leadDays: "Заказ не позже чем за, дней",
    leadDaysHint: "Пусто — как у витрины",
    includesRu: "Что входит (RU)",
    includesUz: "Nima kiradi (UZ)",
    name: "Название",
    includes: "Что входит",
    options: "Дополнения",
  } as Record<string, string>,
  serviceErrors: {
    type: "Выберите услугу из каталога",
    name: "Название на двух языках, от 2 символов",
    priceUzs: "Целое число больше нуля",
    priceUnit: "Выберите единицу этой услуги",
    minQty: "Целое число от 1",
    leadDays: "От 0 до 365 дней",
    includes: "До 1000 символов на каждом языке",
    options: "Не больше 10 дополнений, у каждого — название на двух языках и цена",
  } as Record<string, string>,
  optionsHint: "Платные дополнения к услуге: клиент отмечает их в заявке, цену пишете вы.",
  optionAdd: "Своё дополнение",
  optionFromCatalog: "Дополнение из каталога",
  optionRemove: "Убрать",
  optionN: (n: number) => `Дополнение ${n}`,
  optionError: "Название на двух языках и цена больше нуля",

  // очередь услуг в модерации
  serviceQueue: "Услуги",
  serviceQueueHint:
    "Новые услуги и изменения услуг — от партнёра или менеджера, и у черновиков тоже: партнёр видит «на проверке». Что не решите до публикации, одобрит публикация витрины.",
  serviceQueueEmpty: "Услуг, ждущих решения, нет.",
  serviceQueueKinds: { review: "Новая услуга", proposal: "Изменения услуги" } as Record<string, string>,
  serviceNow: "Сейчас",
  serviceProposed: "Предлагают",
  serviceApprove: "Одобрить",
  serviceDecline: "Отклонить",
  serviceDeclineHint: "Причину увидит партнёр в кабинете.",
  // что решили по услуге в очереди — строкой статуса (фокус уже на следующей)
  serviceApproved: (name: string) => `Одобрено: ${name}. Дальше — следующая услуга.`,
  serviceDeclinedSaid: (name: string) => `Отклонено: ${name}. Дальше — следующая услуга.`,
  // то же на странице витрины
  serviceApprovedHere: (name: string) => `Одобрено: ${name}.`,
  serviceDeclinedHere: (name: string) => `Отклонено: ${name}. Причину увидит партнёр.`,
  guestsUpTo: (n: number) => `до ${n} гостей`,
  // после решения по предложению или витрине на проверке — к следующему в очереди
  nextRevision: (name: string) => `Следующее предложение: ${name}`,
  nextReview: (name: string) => `Следующая на проверке: ${name}`,
  queueDone: "В этой очереди больше ничего не ждёт решения.",
  toModeration: "К модерации",

  // занятость по режимам категорий
  availabilityHints: {
    day: "Отметьте дни, когда витрина занята. Нажмите на день, чтобы отметить или снять.",
    parts:
      "День делится на утро, день и вечер. Нажмите на день, чтобы отметить его целиком или по частям. Часть занята, когда отмечена или договорённостей на неё столько же, сколько заказов одновременно.",
    slot: "Студия: отмечайте дни целиком. Время начала и часы съёмки приходят в заявке.",
  },
  dayParts: { morning: "Утро", day: "День", evening: "Вечер" } as Record<string, string>,
  wholeDay: "Весь день",
  markBusy: "Занять",
  partState: { free: "свободно", busy: "занято", full: "все места заняты" } as Record<string, string>,
  partBookings: (count: number, capacity: number) => `договорённостей: ${count} из ${capacity}`,
  dayLoad: { free: "свободно", partial: "занято частично", busy: "занято" } as Record<string, string>,
  legendPartial: "занято частично",
  capacityNow: (n: number) => `Заказов одновременно: ${n} — меняется в одноимённом блоке формы витрины.`,
  pickedDay: (day: string) => `День: ${day}`,
  leadTitle: "Срок заказа",
  leadHint: "Календаря у этой категории нет: витрина принимает заказы не позже чем за указанный срок.",
  leadDaysValue: (n: number) => `Заказ не позже чем за ${n} дн.`,
  leadNotSet: "Срок не указан — заполните «Заказ не позже чем за, дней» в данных витрины.",
  leadServices: (list: string) => `Свой срок у услуг: ${list}`,

  // заявки по категориям
  dayPart: "Часть дня",
  requestDetails: "Что нужно клиенту",
  requestServices: "Выбранные услуги",

  // ── списки: страницы, фильтры в адресе, пустой список ──
  pagerLabel: "Страницы списка",
  pagerPrev: "Предыдущие",
  pagerNext: "Следующие",
  pagerRange: (from: number, to: number, total: number) => `${from}–${to} из ${total}`,
  showMore: "Показать ещё",
  shownOf: (shown: number, total: number) => `Показано ${shown} из ${total}`,
  resetFilters: "Сбросить фильтры",
  // фильтр вендоров — по статусу их витрин, а не самого вендора
  vendorsListingStatus: "Статус витрины",
  // что значит «Лид» — подсказкой у статуса и в фильтре
  statusHints: {
    lead: "Вендор в работе у команды: витрина ещё не заполнена, клиенты её не видят",
  } as Record<string, string>,
  requestsLeadSla: (hours: number) =>
    `Заявки клиентов и ответы вендоров. Без ответа — вверху, ближайший срок первым; срок ответа — ${hours} ч.`,
  requestStatusFilter: "Статус заявки",
  allStatuses: "Все статусы",
  // заявки одной витрины (?listingId=) — снятый фильтр возвращает все
  requestsOfListing: (name: string) => `Витрина: ${name}`,
  requestsOfListingUnknown: "Одна витрина",
  requestsFilteredEmpty: "Заявок с такими фильтрами нет.",
  clientsFilteredEmpty: "Клиентов с такими фильтрами нет.",
  vendorsFilteredEmpty: "Вендоров с такими фильтрами нет.",

  // ── навигация: путь к странице, переходы между объектами ──
  crumbs: "Путь к странице",
  vendorRequests: "Заявки вендора",
  vendorJournal: "Журнал вендора",
  listingOnSite: "Открыть на сайте",
  opensNewTab: "откроется в новой вкладке",
  listingRequests: "Заявки витрины",
  requestClientOpen: (ref: string) => `Клиент ${ref}`,
  // оглавление страницы витрины на телефоне: к блоку одним нажатием
  listingIndex: "Разделы витрины",
  listingIndexItems: {
    photos: "Фото",
    services: "Услуги",
    calendar: "Занятость",
    main: "Основное",
    attrs: "Данные",
    phone: "Контакты",
    history: "История",
  } as Record<string, string>,
  // опубликовать или отправить на проверку нельзя: чего не хватает — в той же шторке
  actionBlocked: {
    publish: "Опубликовать пока нельзя — не хватает:",
    submit: "Отправить на проверку пока нельзя — не хватает:",
  } as Record<string, string>,

  // ── заявка: бюджет одной границей ──
  budgetRange: (from: string, to: string) => `от ${from} до ${to}`,
  budgetFrom: (from: string) => `от ${from}`,
  budgetTo: (to: string) => `до ${to}`,

  // ── уведомления о сделанном (всплывают внизу и исчезают сами) ──
  toastServicePaused: (name: string) => `«${name}» снята с витрины`,
  toastServiceResumed: (name: string) => `«${name}» снова на витрине`,
  toastServiceSubmitted: (name: string) => `«${name}» отправлена на проверку`,
  toastCover: (n: number) => `Фото ${n} — обложка витрины`,
  toastPhotoApproved: (n: number) => `Фото ${n} одобрено`,
  toastChecklist: (item: string, done: boolean) => (done ? `Отмечено: ${item}` : `Отметка снята: ${item}`),

  // ── фото: выбрали больше предела ──
  photosOverLimit: (uploaded: number, picked: number, max: number) =>
    `Загружено ${uploaded} из ${picked}, предел — ${max} фото на витрине. Остальные не загружены.`,

  // ── новый вендор: что дальше ──
  vendorCreated: "Вендор заведён. Что дальше:",
  vendorNextChecklist: "Проверка вендора: договор, СТИР, звонок, согласие на ПДн",
  vendorNextUsers: "Вход в кабинет: пригласите владельца по номеру телефона",
  vendorNextListing: "Первая витрина: фото, услуги и данные",
  vendorNextDone: "Понятно",

  // ── журнал: объект — поиском, сотрудник — и отключённые ──
  auditObjectAny: "Любой",
  auditObjectSearch: "Найти",
  auditObjectSearching: "Ищем…",
  auditObjectEmpty: "Ничего не нашлось",
  auditObjectHints: {
    vendor: "Название, код или СТИР вендора",
    listing: "Название витрины",
    client: "Код клиента (C-…) или номер заявки",
    request: "Номер заявки",
    staff: "Имя сотрудника",
  } as Record<string, string>,
  // у вида объекта нет поиска (настройка, уведомление) — сначала выбрать другой вид
  auditObjectNoSearch: "Для этого вида объекта поиска нет",
  auditObjectPickType: "Сначала выберите вид объекта",
  auditStaffInactive: (name: string) => `${name} (отключён)`,
  auditActorStaffOnly: "Только когда «Кто» — сотрудник",
} as const;

/** Текст ошибки API по коду */
export function apiErrorText(code: string): string {
  return t.api[code] ?? t.api.unknown ?? "";
}
