/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppActorKind = "client" | "staff" | "system" | "vendor_user";

export type AppConsentAction = "grant" | "withdraw";

export type AppConsentPurpose = "bot_notifications" | "client_service" | "request_transfer" | "vendor_contact" | "vendor_offer" | "vendor_phone_public";

export type AppDeclineReason = "busy" | "format" | "other" | "price";

export type AppLegalForm = "ooo" | "self_employed" | "yatt";

export type AppListingStatus = "active" | "draft" | "lead" | "rejected" | "review" | "suspended";

export type AppLocale = "ru" | "uz";

export type AppModerationStatus = "approved" | "declined" | "pending" | "withdrawn";

export type AppNotifyChannel = "sms" | "telegram";

export type AppOutboxStatus = "dead" | "failed" | "pending" | "sending" | "sent";

export type AppPackageKind = "custom" | "weekday" | "weekend";

export type AppPhotoStatus = "failed" | "processing" | "ready" | "uploading";

export type AppPriceUnit = "per_event" | "per_guest";

export type AppRequestStatus = "contacted" | "deal" | "declined" | "expired" | "new" | "viewed" | "withdrawn";

export type AppSource = "admin" | "offline" | "partner_bot" | "system" | "tma" | "vendor_cabinet" | "web";

export type AppStaffRole = "admin" | "manager" | "moderator";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppAuditLog {
  action: string;
  actor_id: Generated<string | null>;
  actor_kind: Generated<AppActorKind>;
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  ip_hash: Uint8Array | null;
  object_id: string;
  object_type: string;
  source: AppSource | null;
  trace_id: string | null;
}

export interface AppAvailability {
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  day: string;
  listing_id: string;
  request_id: string | null;
  source: Generated<string>;
}

export interface AppCategories {
  code: string;
  enabled: Generated<boolean>;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppClients {
  blocked_at: Timestamp | null;
  blocked_by: string | null;
  blocked_reason: string | null;
  can_message: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  locale: Generated<AppLocale>;
  tg_id_hash: Uint8Array;
  updated_at: Generated<Timestamp>;
}

export interface AppConsents {
  action: AppConsentAction;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  purpose: AppConsentPurpose;
  recorded_by: string | null;
  scope_listing_id: string | null;
  source: AppSource;
  subject_id: string;
  subject_kind: AppActorKind;
  text_id: string;
}

export interface AppConsentsCurrent {
  action: AppConsentAction | null;
  created_at: Timestamp | null;
  id: string | null;
  ip_hash: Uint8Array | null;
  purpose: AppConsentPurpose | null;
  recorded_by: string | null;
  scope_listing_id: string | null;
  source: AppSource | null;
  subject_id: string | null;
  subject_kind: AppActorKind | null;
  text_id: string | null;
}

export interface AppConsentTexts {
  body: string;
  body_sha256: Uint8Array;
  id: Generated<string>;
  legal_entity_id: string | null;
  locale: AppLocale;
  published_at: Generated<Timestamp>;
  purpose: AppConsentPurpose;
  recipients: Generated<string[]>;
  retired_at: Timestamp | null;
  version: number;
}

export interface AppDistricts {
  code: string;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppLegalEntities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  registered_on: string | null;
  stir: string | null;
}

export interface AppListingPackages {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: AppPackageKind;
  listing_id: string;
  name_ru: string;
  name_uz: string;
  price_unit: Generated<AppPriceUnit>;
  price_uzs: Int8;
  sort: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface AppListingRevisions {
  base_version: number;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  listing_id: string;
  payload: Json;
  status: Generated<AppModerationStatus>;
  submitted_at: Generated<Timestamp>;
  submitted_by: string | null;
}

export interface AppListings {
  address_ru: string | null;
  address_uz: string | null;
  cap_max: number | null;
  cap_min: number | null;
  category_code: string;
  created_at: Generated<Timestamp>;
  description_ru: string | null;
  description_uz: string | null;
  district_code: string | null;
  id: Generated<string>;
  name: string;
  price_from_uzs: Int8 | null;
  price_unit: Generated<AppPriceUnit>;
  published_at: Timestamp | null;
  slug: string;
  status: Generated<AppListingStatus>;
  status_changed_at: Timestamp | null;
  status_changed_by: string | null;
  status_reason: string | null;
  submitted_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
  version: Generated<number>;
}

export interface AppListingStatusLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  from_status: AppListingStatus | null;
  id: Generated<Int8>;
  listing_id: string;
  reason: string | null;
  to_status: AppListingStatus;
}

export interface AppOccasions {
  code: string;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppOtpCodes {
  attempts: Generated<number>;
  code_hash: Uint8Array;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  phone_hash: Uint8Array;
  provider: string;
  provider_msg_id: string | null;
}

export interface AppOutbox {
  attempts: Generated<number>;
  channel: Generated<AppNotifyChannel>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  /**
   * Когда строку взял отправитель (status = sending)
   */
  enqueued_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Generated<Json>;
  provider_msg_id: string | null;
  recipient_id: string | null;
  recipient_kind: AppActorKind;
  request_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<AppOutboxStatus>;
}

export interface AppPhotos {
  bytes: number | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  failure_reason: string | null;
  height: number | null;
  id: Generated<string>;
  is_cover: Generated<boolean>;
  listing_id: string;
  mime: string | null;
  moderated_at: Timestamp | null;
  moderated_by: string | null;
  moderation: Generated<AppModerationStatus>;
  no_faces_ack: boolean;
  processed_at: Timestamp | null;
  /**
   * sha256 файла: один и тот же файл дважды в листинг не загрузить
   */
  sha256: Uint8Array | null;
  sort: Generated<number>;
  status: Generated<AppPhotoStatus>;
  /**
   * Ключ объекта в бакете listing-photos: listings/<listing_id>/<uuid>.<webp|jpg|png>
   */
  storage_key: string;
  uploaded_by: string | null;
  width: number | null;
}

export interface AppPiiAccessLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  field: string;
  id: Generated<Int8>;
  purpose: string;
  reason: string | null;
  subject_id: string;
  subject_kind: string;
}

export interface AppRequests {
  budget_max_uzs: Int8 | null;
  budget_min_uzs: Int8 | null;
  client_id: string;
  consent_id: string;
  created_at: Generated<Timestamp>;
  decline_note: string | null;
  decline_reason: AppDeclineReason | null;
  event_date: string;
  first_response_at: Timestamp | null;
  first_response_by: AppActorKind | null;
  first_viewed_at: Timestamp | null;
  guests: number;
  id: Generated<string>;
  listing_id: string;
  occasion_code: string;
  public_no: Generated<Int8>;
  sla_breached_at: Timestamp | null;
  sla_due_at: Timestamp;
  sla_stage: Generated<number>;
  source: AppSource;
  status: Generated<AppRequestStatus>;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface AppRequestStatusLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  from_status: AppRequestStatus | null;
  id: Generated<Int8>;
  reason: string | null;
  request_id: string;
  source: AppSource;
  to_status: AppRequestStatus;
}

export interface AppRequestTransitions {
  actor: AppActorKind;
  from_status: AppRequestStatus;
  to_status: AppRequestStatus;
}

export interface AppSessions {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  last_seen_at: Timestamp | null;
  revoked_at: Timestamp | null;
  staff_id: string | null;
  token_hash: Uint8Array;
  vendor_user_id: string | null;
  via: string;
}

export interface AppSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface AppStaff {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: AppStaffRole;
  /**
   * HMAC-SHA256(ID_HASH_KEY, Telegram ID); null — приглашение ещё не принято
   */
  tg_id_hash: Uint8Array | null;
  tg_linked_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface AppTelegramUpdates {
  received_at: Generated<Timestamp>;
  update_id: Int8;
}

export interface AppVendorAccounts {
  contacts_confirmed_at: Timestamp | null;
  contacts_confirmed_by: string | null;
  contract_checked_by: string | null;
  contract_no: string | null;
  contract_signed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  legal_form: AppLegalForm | null;
  manager_id: string | null;
  /**
   * Название для панели и поиска (бренд). Юрназвание и СТИР — в pii.vendor_contacts
   */
  name: string | null;
  pd_consent_checked_by: string | null;
  pd_consent_signed_at: Timestamp | null;
  pd_consent_text_id: string | null;
  public_code: Generated<string>;
  stir_verified_at: Timestamp | null;
  stir_verified_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AppVendorUsers {
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locale: Generated<AppLocale>;
  phone_hash: Uint8Array;
  role: Generated<string>;
  tg_linked_at: Timestamp | null;
  tg_user_hash: Uint8Array | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface PiiClientProfiles {
  client_id: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  phone_verified_at: Timestamp | null;
  telegram_id: Int8;
  updated_at: Generated<Timestamp>;
  username: string | null;
}

export interface PiiListingContacts {
  listing_id: string;
  public_phone: string;
  updated_at: Generated<Timestamp>;
}

export interface PiiRequestContacts {
  comment: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  purged_at: Timestamp | null;
  request_id: string;
}

export interface PiiStaffProfiles {
  display_name: string;
  email: string | null;
  staff_id: string;
  telegram_chat_id: Int8 | null;
  telegram_id: Int8 | null;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PiiVendorContacts {
  contact_person: string | null;
  contact_role: string | null;
  legal_address: string | null;
  legal_name: string | null;
  phone: string | null;
  phone_alt: string | null;
  stir: string | null;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface PiiVendorUserProfiles {
  full_name: string | null;
  phone: string;
  telegram_chat_id: Int8 | null;
  telegram_user_id: Int8 | null;
  updated_at: Generated<Timestamp>;
  vendor_user_id: string;
}

export interface DB {
  "app.audit_log": AppAuditLog;
  "app.availability": AppAvailability;
  "app.categories": AppCategories;
  "app.clients": AppClients;
  "app.consent_texts": AppConsentTexts;
  "app.consents": AppConsents;
  "app.consents_current": AppConsentsCurrent;
  "app.districts": AppDistricts;
  "app.legal_entities": AppLegalEntities;
  "app.listing_packages": AppListingPackages;
  "app.listing_revisions": AppListingRevisions;
  "app.listing_status_log": AppListingStatusLog;
  "app.listings": AppListings;
  "app.occasions": AppOccasions;
  "app.otp_codes": AppOtpCodes;
  "app.outbox": AppOutbox;
  "app.photos": AppPhotos;
  "app.pii_access_log": AppPiiAccessLog;
  "app.request_status_log": AppRequestStatusLog;
  "app.request_transitions": AppRequestTransitions;
  "app.requests": AppRequests;
  "app.sessions": AppSessions;
  "app.settings": AppSettings;
  "app.staff": AppStaff;
  "app.telegram_updates": AppTelegramUpdates;
  "app.vendor_accounts": AppVendorAccounts;
  "app.vendor_users": AppVendorUsers;
  "pii.client_profiles": PiiClientProfiles;
  "pii.listing_contacts": PiiListingContacts;
  "pii.request_contacts": PiiRequestContacts;
  "pii.staff_profiles": PiiStaffProfiles;
  "pii.vendor_contacts": PiiVendorContacts;
  "pii.vendor_user_profiles": PiiVendorUserProfiles;
}
