/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppActorKind = "account" | "client" | "staff" | "system" | "vendor_user";

export type AppAvailabilityMode = "day" | "lead" | "parts" | "slot";

export type AppConsentAction = "grant" | "withdraw";

export type AppConsentPurpose = "bot_notifications" | "client_service" | "request_transfer" | "vendor_contact" | "vendor_offer" | "vendor_phone_public";

export type AppDayPart = "day" | "evening" | "morning";

export type AppDeclineReason = "busy" | "format" | "other" | "price";

export type AppIdentityKind = "phone" | "telegram";

export type AppLegalForm = "ooo" | "self_employed" | "yatt";

export type AppListingStatus = "active" | "draft" | "lead" | "rejected" | "review" | "suspended";

export type AppLocale = "ru" | "uz";

export type AppModerationStatus = "approved" | "declined" | "pending" | "withdrawn";

export type AppNotifyChannel = "sms" | "telegram";

export type AppOutboxStatus = "dead" | "failed" | "pending" | "sending" | "sent";

export type AppPhotoPolicy = "no_people" | "portfolio";

export type AppPhotoStatus = "failed" | "processing" | "ready" | "uploading";

export type AppPriceUnit = "per_event" | "per_guest" | "per_hour" | "per_item" | "per_kg" | "per_set" | "per_table";

export type AppRequestStatus = "contacted" | "deal" | "declined" | "expired" | "new" | "viewed" | "withdrawn";

export type AppServiceStatus = "active" | "draft" | "paused" | "rejected" | "review";

export type AppServiceTier = "base" | "extra";

export type AppSource = "admin" | "offline" | "partner_bot" | "system" | "tma" | "vendor_cabinet" | "web";

export type AppStaffRole = "admin" | "manager" | "moderator";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppAccountIdentities {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: AppIdentityKind;
  last_used_at: Timestamp | null;
  value_hash: Uint8Array;
  verified_at: Generated<Timestamp>;
}

export interface AppAccounts {
  created_at: Generated<Timestamp>;
  /**
   * Удалён самим человеком: профиль стёрт, членства отвязаны; вход тем же способом восстанавливает аккаунт
   */
  deleted_at: Timestamp | null;
  /**
   * Отключён сотрудником: все роли и сессии сразу
   */
  disabled_at: Timestamp | null;
  disabled_by: string | null;
  disabled_reason: string | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  locale: Generated<AppLocale>;
  updated_at: Generated<Timestamp>;
}

export interface AppApiErrorAlerts {
  errors: Generated<number>;
  id: Generated<number>;
  last_alert_at: Timestamp | null;
  last_error_at: Timestamp | null;
  last_route: string | null;
}

export interface AppAuditLog {
  action: string;
  actor_id: Generated<string | null>;
  actor_kind: Generated<AppActorKind>;
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  ip_hash: Uint8Array | null;
  object_id: string;
  object_type: string;
  source: AppSource | null;
  trace_id: string | null;
}

export interface AppAvailability {
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  day: string;
  listing_id: string;
  request_id: string | null;
  /**
   * vendor — отметил вендор; request_decline — отказ «занято» по заявке request_id; staff — закрыл сотрудник
   */
  source: Generated<string>;
}

export interface AppAvailabilityParts {
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  day: string;
  listing_id: string;
  part: AppDayPart;
  request_id: string | null;
  source: Generated<string>;
}

export interface AppAvailabilityVersions {
  listing_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AppCategories {
  availability_mode: Generated<AppAvailabilityMode>;
  code: string;
  enabled: Generated<boolean>;
  max_video_links: Generated<number>;
  min_photos: Generated<number>;
  name_ru: string;
  name_uz: string;
  photo_policy: Generated<AppPhotoPolicy>;
  required_attributes: Generated<string[]>;
  required_fields: Generated<string[]>;
  required_services: Generated<string[]>;
  sort: Generated<number>;
}

export interface AppCities {
  code: string;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppClients {
  account_id: string;
  blocked_at: Timestamp | null;
  blocked_by: string | null;
  blocked_reason: string | null;
  can_message: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  locale: Generated<AppLocale>;
  /**
   * HMAC(ID_HASH_KEY, Telegram ID) аккаунта; null — у аккаунта нет Telegram (вход по телефону)
   */
  tg_id_hash: Uint8Array | null;
  updated_at: Generated<Timestamp>;
}

export interface AppConsents {
  action: AppConsentAction;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  purpose: AppConsentPurpose;
  recorded_by: string | null;
  scope_listing_id: string | null;
  source: AppSource;
  subject_id: string;
  subject_kind: AppActorKind;
  text_id: string;
}

export interface AppConsentsCurrent {
  action: AppConsentAction | null;
  created_at: Timestamp | null;
  id: string | null;
  ip_hash: Uint8Array | null;
  purpose: AppConsentPurpose | null;
  recorded_by: string | null;
  scope_listing_id: string | null;
  source: AppSource | null;
  subject_id: string | null;
  subject_kind: AppActorKind | null;
  text_id: string | null;
}

export interface AppConsentTexts {
  body: string;
  body_sha256: Uint8Array;
  id: Generated<string>;
  legal_entity_id: string | null;
  locale: AppLocale;
  published_at: Generated<Timestamp>;
  purpose: AppConsentPurpose;
  recipients: Generated<string[]>;
  retired_at: Timestamp | null;
  version: number;
}

export interface AppContactEvents {
  action: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  listing_id: string;
  signed_in: boolean;
  source: AppSource;
}

export interface AppDistricts {
  /**
   * Город района
   */
  city_code: string;
  code: string;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppFavorites {
  client_id: string;
  created_at: Generated<Timestamp>;
  listing_id: string;
}

export interface AppHubCodes {
  account_id: string;
  app: string;
  challenge: string;
  code_hash: Uint8Array;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  origin: string;
  proof_at: Timestamp;
  state_hash: Uint8Array;
  used_at: Timestamp | null;
}

export interface AppLegalEntities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  registered_on: string | null;
  stir: string | null;
}

export interface AppListingRevisions {
  base_version: number;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  listing_id: string;
  payload: Json;
  status: Generated<AppModerationStatus>;
  submitted_at: Generated<Timestamp>;
  submitted_by: string | null;
}

export interface AppListings {
  address_ru: string | null;
  address_uz: string | null;
  /**
   * Поля витрины категории (packages/shared/src/categories): структуру проверяет API
   */
  attributes: Generated<Json>;
  cap_max: number | null;
  cap_min: number | null;
  category_code: string;
  created_at: Generated<Timestamp>;
  description_ru: string | null;
  description_uz: string | null;
  district_code: string | null;
  id: Generated<string>;
  name: string;
  /**
   * Сколько заказов витрина берёт одновременно (режим занятости parts): экипажи, машины
   */
  parallel_capacity: Generated<number>;
  /**
   * Цена «от»: самая низкая цена услуг, входящих в цену «от» (app.listing_price_from). Пишет только триггер
   */
  price_from_uzs: Int8 | null;
  price_unit: Generated<AppPriceUnit>;
  published_at: Timestamp | null;
  slug: string;
  status: Generated<AppListingStatus>;
  status_changed_at: Timestamp | null;
  status_changed_by: string | null;
  status_reason: string | null;
  submitted_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
  version: Generated<number>;
  video_links: Generated<string[]>;
}

export interface AppListingServices {
  category_code: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  includes_ru: string | null;
  includes_uz: string | null;
  lead_days: number | null;
  listing_id: string;
  min_qty: number | null;
  name_ru: string | null;
  name_uz: string | null;
  options: Generated<Json>;
  price_unit: AppPriceUnit;
  price_uzs: Int8;
  proposal: Json | null;
  proposal_at: Timestamp | null;
  proposal_by: string | null;
  service_type: string;
  sort: Generated<number>;
  status: Generated<AppServiceStatus>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AppListingStatusLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  from_status: AppListingStatus | null;
  id: Generated<Int8>;
  listing_id: string;
  reason: string | null;
  to_status: AppListingStatus;
}

export interface AppOccasions {
  code: string;
  name_ru: string;
  name_uz: string;
  sort: Generated<number>;
}

export interface AppOtpCodes {
  attempts: Generated<number>;
  /**
   * HMAC(ID_HASH_KEY, "otp:<номер>:<код>")
   */
  code_hash: Uint8Array;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  phone_hash: Uint8Array;
  provider: string;
  provider_msg_id: string | null;
}

export interface AppOutbox {
  attempts: Generated<number>;
  channel: Generated<AppNotifyChannel>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  /**
   * Когда строку взял отправитель (status = sending)
   */
  enqueued_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Generated<Json>;
  provider_msg_id: string | null;
  recipient_id: string | null;
  recipient_kind: AppActorKind;
  request_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<AppOutboxStatus>;
}

export interface AppPhotos {
  bytes: number | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  failure_reason: string | null;
  height: number | null;
  id: Generated<string>;
  is_cover: Generated<boolean>;
  listing_id: string;
  mime: string | null;
  moderated_at: Timestamp | null;
  moderated_by: string | null;
  moderation: Generated<AppModerationStatus>;
  /**
   * Причина отказа модератора — только у отклонённого фото; партнёр видит её в кабинете
   */
  moderation_reason: string | null;
  no_faces_ack: Generated<boolean>;
  /**
   * Загрузивший подтвердил согласие людей на фото — только у категорий с правилом portfolio
   */
  people_consent_ack: Generated<boolean>;
  processed_at: Timestamp | null;
  /**
   * sha256 файла: один и тот же файл дважды в листинг не загрузить
   */
  sha256: Uint8Array | null;
  sort: Generated<number>;
  status: Generated<AppPhotoStatus>;
  /**
   * Ключ объекта в бакете listing-photos: listings/<listing_id>/<uuid>.<webp|jpg|png>
   */
  storage_key: string;
  uploaded_by: string | null;
  width: number | null;
}

export interface AppPiiAccessLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  field: string;
  id: Generated<Int8>;
  purpose: string;
  reason: string | null;
  subject_id: string;
  subject_kind: string;
}

export interface AppRequestMetricFacts {
  agreed: boolean | null;
  answered_in_time: boolean | null;
  breached: boolean | null;
  category_code: string | null;
  client_id: string | null;
  closed_at: Timestamp | null;
  created_at: Timestamp | null;
  listing_id: string | null;
  measurable: boolean | null;
  request_id: string | null;
  response_minutes: number | null;
  sla_due_at: Timestamp | null;
  status: AppRequestStatus | null;
  vendor_id: string | null;
  vendor_response_at: Timestamp | null;
}

export interface AppRequestNotes {
  author_id: Generated<string>;
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  request_id: string;
}

export interface AppRequests {
  budget_max_uzs: Int8 | null;
  budget_min_uzs: Int8 | null;
  client_id: string;
  consent_id: string;
  created_at: Generated<Timestamp>;
  /**
   * Часть дня (режим занятости parts): API выводит её из времени начала в details
   */
  day_part: AppDayPart | null;
  decline_note: string | null;
  decline_reason: AppDeclineReason | null;
  /**
   * Поля формы заявки категории (packages/shared/src/categories): без ПДн и свободного текста, проверяет API
   */
  details: Generated<Json>;
  event_date: string;
  first_response_at: Timestamp | null;
  first_response_by: AppActorKind | null;
  first_viewed_at: Timestamp | null;
  guests: number | null;
  id: Generated<string>;
  listing_id: string;
  occasion_code: string;
  public_no: Generated<Int8>;
  sla_breached_at: Timestamp | null;
  sla_due_at: Timestamp;
  sla_stage: Generated<number>;
  source: AppSource;
  status: Generated<AppRequestStatus>;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface AppRequestStatusLog {
  actor_id: string | null;
  actor_kind: AppActorKind;
  at: Generated<Timestamp>;
  from_status: AppRequestStatus | null;
  id: Generated<Int8>;
  reason: string | null;
  request_id: string;
  source: AppSource;
  to_status: AppRequestStatus;
}

export interface AppRequestTransitions {
  actor: AppActorKind;
  from_status: AppRequestStatus;
  to_status: AppRequestStatus;
}

export interface AppServiceTypes {
  category_code: string;
  code: string;
  enabled: Generated<boolean>;
  free_name: Generated<boolean>;
  in_price_from: Generated<boolean>;
  name_ru: string;
  name_uz: string;
  options: Generated<Json>;
  sort: Generated<number>;
  tier: Generated<AppServiceTier>;
  units: ArrayType<AppPriceUnit>;
}

export interface AppSessions {
  account_id: string;
  app: string;
  client_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_hash: Uint8Array | null;
  last_seen_at: Timestamp | null;
  proof_at: Timestamp;
  revoked_at: Timestamp | null;
  staff_id: string | null;
  token_hash: Uint8Array;
  vendor_user_id: string | null;
  via: string;
}

export interface AppSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface AppStaff {
  /**
   * Аккаунт сотрудника; null — приглашение ещё не принято
   */
  account_id: string | null;
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Приглашение по телефону: HMAC(ID_HASH_KEY, +998XXXXXXXXX); принимается кодом из сообщения
   */
  phone_hash: Uint8Array | null;
  role: AppStaffRole;
  /**
   * HMAC-SHA256(ID_HASH_KEY, Telegram ID) аккаунта сотрудника — оповещения команды; null — Telegram не привязан
   */
  tg_id_hash: Uint8Array | null;
  tg_linked_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface AppTelegramUpdates {
  received_at: Generated<Timestamp>;
  update_id: Int8;
}

export interface AppVendorAccounts {
  contacts_confirmed_at: Timestamp | null;
  contacts_confirmed_by: string | null;
  contract_checked_by: string | null;
  contract_no: string | null;
  contract_signed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  legal_form: AppLegalForm | null;
  manager_id: string | null;
  /**
   * Название для панели и поиска (бренд). Юрназвание и СТИР — в pii.vendor_contacts
   */
  name: string | null;
  pd_consent_checked_by: string | null;
  pd_consent_signed_at: Timestamp | null;
  pd_consent_text_id: string | null;
  public_code: Generated<string>;
  stir_verified_at: Timestamp | null;
  stir_verified_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AppVendorUsers {
  /**
   * Аккаунт партнёра; null — пользователь заведён сотрудником и ещё не подтвердил номер
   */
  account_id: string | null;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locale: Generated<AppLocale>;
  phone_hash: Uint8Array;
  role: Generated<string>;
  tg_linked_at: Timestamp | null;
  /**
   * HMAC Telegram ID аккаунта — уведомления о заявках в Telegram; null — не привязан
   */
  tg_user_hash: Uint8Array | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface PiiAccountProfiles {
  account_id: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  phone_verified_at: Timestamp | null;
  telegram_id: Int8 | null;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PiiClientProfiles {
  client_id: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  phone_verified_at: Timestamp | null;
  telegram_id: Int8;
  updated_at: Generated<Timestamp>;
  username: string | null;
}

export interface PiiListingContacts {
  listing_id: string;
  public_phone: string;
  /**
   * Telegram витрины для клиентов (имя без @); читать — pii.read_listing_contacts / reveal_listing_contacts
   */
  public_telegram: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PiiRequestContacts {
  comment: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  purged_at: Timestamp | null;
  request_id: string;
}

export interface PiiStaffProfiles {
  display_name: string;
  email: string | null;
  staff_id: string;
  telegram_chat_id: Int8 | null;
  telegram_id: Int8 | null;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PiiVendorContacts {
  contact_person: string | null;
  contact_role: string | null;
  legal_address: string | null;
  legal_name: string | null;
  phone: string | null;
  phone_alt: string | null;
  stir: string | null;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface PiiVendorUserProfiles {
  full_name: string | null;
  phone: string;
  telegram_chat_id: Int8 | null;
  telegram_user_id: Int8 | null;
  updated_at: Generated<Timestamp>;
  vendor_user_id: string;
}

export interface DB {
  "app.account_identities": AppAccountIdentities;
  "app.accounts": AppAccounts;
  "app.api_error_alerts": AppApiErrorAlerts;
  "app.audit_log": AppAuditLog;
  "app.availability": AppAvailability;
  "app.availability_parts": AppAvailabilityParts;
  "app.availability_versions": AppAvailabilityVersions;
  "app.categories": AppCategories;
  "app.cities": AppCities;
  "app.clients": AppClients;
  "app.consent_texts": AppConsentTexts;
  "app.consents": AppConsents;
  "app.consents_current": AppConsentsCurrent;
  "app.contact_events": AppContactEvents;
  "app.districts": AppDistricts;
  "app.favorites": AppFavorites;
  "app.hub_codes": AppHubCodes;
  "app.legal_entities": AppLegalEntities;
  "app.listing_revisions": AppListingRevisions;
  "app.listing_services": AppListingServices;
  "app.listing_status_log": AppListingStatusLog;
  "app.listings": AppListings;
  "app.occasions": AppOccasions;
  "app.otp_codes": AppOtpCodes;
  "app.outbox": AppOutbox;
  "app.photos": AppPhotos;
  "app.pii_access_log": AppPiiAccessLog;
  "app.request_metric_facts": AppRequestMetricFacts;
  "app.request_notes": AppRequestNotes;
  "app.request_status_log": AppRequestStatusLog;
  "app.request_transitions": AppRequestTransitions;
  "app.requests": AppRequests;
  "app.service_types": AppServiceTypes;
  "app.sessions": AppSessions;
  "app.settings": AppSettings;
  "app.staff": AppStaff;
  "app.telegram_updates": AppTelegramUpdates;
  "app.vendor_accounts": AppVendorAccounts;
  "app.vendor_users": AppVendorUsers;
  "pii.account_profiles": PiiAccountProfiles;
  "pii.client_profiles": PiiClientProfiles;
  "pii.listing_contacts": PiiListingContacts;
  "pii.request_contacts": PiiRequestContacts;
  "pii.staff_profiles": PiiStaffProfiles;
  "pii.vendor_contacts": PiiVendorContacts;
  "pii.vendor_user_profiles": PiiVendorUserProfiles;
}
